# Feature Engineering with HOG

In this section, we'll implement Histogram of Oriented Gradients (HOG) feature extraction for our frames. HOG is particularly effective for object detection as it captures local gradient information.

In [ ]:
import cv2
from skimage.feature import hog
from skimage.transform import resize
import numpy as np
from tqdm import tqdm

def extract_hog_features(image_path, target_size=(224, 224)):
    """
    Extract HOG features from an image
    
    Args:
        image_path: Path to the image file
        target_size: Target size for resizing
        
    Returns:
        HOG features array
    """
    # Read and resize image
    image = cv2.imread(image_path)
    image = cv2.resize(image, target_size)
    
    # Convert to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    # Extract HOG features
    features, hog_image = hog(
        gray,
        orientations=9,
        pixels_per_cell=(8, 8),
        cells_per_block=(2, 2),
        visualize=True,
        block_norm='L2-Hys'
    )
    
    return features

def process_dataset_hog_features(frame_paths, target_size=(224, 224)):
    """
    Extract HOG features for multiple images
    
    Args:
        frame_paths: List of image file paths
        target_size: Target size for resizing
        
    Returns:
        Array of HOG features
    """
    features_list = []
    
    for path in tqdm(frame_paths, desc="Extracting HOG features"):
        features = extract_hog_features(path, target_size)
        features_list.append(features)
    
    return np.array(features_list)

# Example usage
def prepare_hog_features():
    """
    Prepare HOG features for both training and test sets
    """
    # Get paths for training data
    train_normal_paths = [os.path.join('processed_frames/train/normal', f) 
                         for f in os.listdir('processed_frames/train/normal')
                         if f.endswith(('.jpg', '.jpeg', '.png'))]
    
    train_shoplifting_paths = [os.path.join('processed_frames/train/shoplifting', f)
                              for f in os.listdir('processed_frames/train/shoplifting')
                              if f.endswith(('.jpg', '.jpeg', '.png'))]
    
    # Get paths for test data
    test_normal_paths = [os.path.join('processed_frames/test/normal', f)
                        for f in os.listdir('processed_frames/test/normal')
                        if f.endswith(('.jpg', '.jpeg', '.png'))]
    
    test_shoplifting_paths = [os.path.join('processed_frames/test/shoplifting', f)
                             for f in os.listdir('processed_frames/test/shoplifting')
                             if f.endswith(('.jpg', '.jpeg', '.png'))]
    
    print("Extracting HOG features for training set...")
    train_normal_features = process_dataset_hog_features(train_normal_paths)
    train_shoplifting_features = process_dataset_hog_features(train_shoplifting_paths)
    
    print("\nExtracting HOG features for test set...")
    test_normal_features = process_dataset_hog_features(test_normal_paths)
    test_shoplifting_features = process_dataset_hog_features(test_shoplifting_paths)
    
    # Create labels
    train_labels = np.concatenate([
        np.zeros(len(train_normal_features)),  # 0 for normal
        np.ones(len(train_shoplifting_features))  # 1 for shoplifting
    ])
    
    test_labels = np.concatenate([
        np.zeros(len(test_normal_features)),  # 0 for normal
        np.ones(len(test_shoplifting_features))  # 1 for shoplifting
    ])
    
    # Combine features
    X_train = np.vstack([train_normal_features, train_shoplifting_features])
    X_test = np.vstack([test_normal_features, test_shoplifting_features])
    
    return X_train, X_test, train_labels, test_labels

# Extract features
print("Starting HOG feature extraction...")
X_train, X_test, y_train, y_test = prepare_hog_features()

print("\nFeature extraction complete!")
print(f"Training set shape: {X_train.shape}")
print(f"Test set shape: {X_test.shape}")
print(f"Training labels shape: {y_train.shape}")
print(f"Test labels shape: {y_test.shape}")

# Model Setup - EfficientNetV2B0

Now we'll set up our model using EfficientNetV2B0 as the base model with frozen layers and add our custom classification layers on top.

In [ ]:
import tensorflow as tf
from tensorflow.keras.applications import EfficientNetV2B0
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.regularizers import l2

def create_model(input_shape=(224, 224, 3)):
    """
    Create and compile the model using EfficientNetV2B0 as base
    
    Args:
        input_shape: Input shape for the model
        
    Returns:
        Compiled model
    """
    # Load the base model with pre-trained weights
    base_model = EfficientNetV2B0(
        weights='imagenet',
        include_top=False,
        input_shape=input_shape
    )
    
    # Freeze the base model layers
    for layer in base_model.layers:
        layer.trainable = False
    
    # Add custom layers on top
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(512, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = Dropout(0.5)(x)
    x = Dense(256, activation='relu', kernel_regularizer=l2(0.001))(x)
    x = Dropout(0.3)(x)
    outputs = Dense(1, activation='sigmoid')(x)
    
    # Create the final model
    model = Model(inputs=base_model.input, outputs=outputs)
    
    # Compile the model
    model.compile(
        optimizer=tf.keras.optimizers.Adam(),
        loss='binary_crossentropy',
        metrics=[
            'accuracy',
            tf.keras.metrics.Precision(),
            tf.keras.metrics.Recall()
        ]
    )
    
    return model

# Create the model
model = create_model()
model.summary()

# Data Augmentation

Set up data augmentation pipeline to increase dataset diversity and improve model generalization.

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Create data generators with augmentation for training
train_datagen = ImageDataGenerator(
    rescale=1./255,  # Normalize pixel values
    rotation_range=20,  # Random rotation
    width_shift_range=0.2,  # Random horizontal shift
    height_shift_range=0.2,  # Random vertical shift
    horizontal_flip=True,  # Random horizontal flip
    zoom_range=0.2,  # Random zoom
    fill_mode='nearest'  # Strategy for filling new pixels
)

# Create data generator for validation (only rescaling)
test_datagen = ImageDataGenerator(rescale=1./255)

# Set up the generators
batch_size = 32

train_generator = train_datagen.flow_from_directory(
    'processed_frames/train',
    target_size=(224, 224),
    batch_size=batch_size,
    class_mode='binary',
    classes=['normal', 'shoplifting']
)

test_generator = test_datagen.flow_from_directory(
    'processed_frames/test',
    target_size=(224, 224),
    batch_size=batch_size,
    class_mode='binary',
    classes=['normal', 'shoplifting']
)

print("Data generators created successfully!")
print(f"Training samples: {train_generator.samples}")
print(f"Testing samples: {test_generator.samples}")
print(f"Class mapping: {train_generator.class_indices}")

# Model Training

Train the model using our prepared data generators with proper callbacks for monitoring and saving the best model.

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
import matplotlib.pyplot as plt

# Set up callbacks
callbacks = [
    ModelCheckpoint(
        'best_model.h5',
        monitor='val_accuracy',
        save_best_only=True,
        mode='max',
        verbose=1
    ),
    EarlyStopping(
        monitor='val_loss',
        patience=10,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=5,
        min_lr=1e-6,
        verbose=1
    )
]

# Train the model
epochs = 50
steps_per_epoch = train_generator.samples // batch_size
validation_steps = test_generator.samples // batch_size

history = model.fit(
    train_generator,
    steps_per_epoch=steps_per_epoch,
    epochs=epochs,
    validation_data=test_generator,
    validation_steps=validation_steps,
    callbacks=callbacks
)

# Plot training history
plt.figure(figsize=(12, 4))

# Plot training & validation accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plot training & validation loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

plt.tight_layout()
plt.show()

# Model Evaluation

Evaluate the model's performance using various metrics including accuracy, precision, recall, F1 score, and confusion matrix.

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

def evaluate_model(model, test_generator):
    """
    Evaluate the model and print various metrics
    """
    # Get predictions
    test_generator.reset()
    y_pred = model.predict(test_generator, steps=len(test_generator))
    y_pred_classes = (y_pred > 0.5).astype(int)
    
    # Get true labels
    y_true = test_generator.classes
    
    # Print classification report
    print("\nClassification Report:")
    print("--------------------")
    print(classification_report(y_true, y_pred_classes, target_names=['Normal', 'Shoplifting']))
    
    # Calculate and plot confusion matrix
    cm = confusion_matrix(y_true, y_pred_classes)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Normal', 'Shoplifting'],
                yticklabels=['Normal', 'Shoplifting'])
    plt.title('Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()
    
    # Print additional metrics
    test_loss, test_acc, test_precision, test_recall = model.evaluate(test_generator)
    f1_score = 2 * (test_precision * test_recall) / (test_precision + test_recall)
    
    print("\nFinal Metrics:")
    print("-------------")
    print(f"Test Accuracy: {test_acc:.4f}")
    print(f"Test Precision: {test_precision:.4f}")
    print(f"Test Recall: {test_recall:.4f}")
    print(f"Test F1 Score: {f1_score:.4f}")

# Evaluate the model
print("Evaluating model performance...")
evaluate_model(model, test_generator)

In [ ]:
import pandas as pd

# Feature Extraction Process

This notebook implements deep feature extraction from surveillance video frames using the following steps:

1. **Dataset Organization**
   - Organizes videos from DCSASS dataset into shoplifting and non-shoplifting categories
   - Separates data into training and testing sets

2. **Frame Extraction**
   - Extracts frames from videos at regular intervals
   - Processes both shoplifting and normal videos
   - Saves frames in organized directory structure

3. **Feature Extraction**
   - Uses pre-trained VGG16 model
   - Processes frames in memory-efficient batches
   - Applies feature standardization
   - Saves extracted features as NumPy arrays

4. **Output**
   - `train_features.npy`: Features from training set frames
   - `train_labels.npy`: Labels for training set
   - `test_features.npy`: Features from testing set frames
   - `test_labels.npy`: Labels for testing set

The features can then be used for training a shoplifting detection model.

In [ ]:
import os
import cv2
import random
import numpy as np
from tqdm import tqdm
from tensorflow.keras.applications.vgg16 import VGG16, preprocess_input
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.preprocessing import StandardScaler

In [ ]:
import cv2
import os

In [10]:
import zipfile
import os

def unzip_file(zip_file, extract_to):
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
        zip_ref.extractall(extract_to)

# Replace 'folder_archiv.zip' with the actual name of your ZIP file
zip_file = 'archive.zip'

# Replace 'extracted_folder' with the directory where you want to extract the contents
extract_to = 'extracted_folder'

# Create the extraction directory if it doesn't exist
if not os.path.exists(extract_to):
    os.makedirs(extract_to)

# Call the function to unzip the file
unzip_file(zip_file, extract_to)

print("Extraction complete!")

Extraction complete!

In [11]:
import pandas as pd
import os

def create_dataset_csv(dataset_path, output_csv="data/shoplifting.csv"):
    """
    Create a CSV file that organizes the DCSASS dataset for training
    """
    # Find all video files
    video_extensions = ['.mp4', '.avi', '.mov', '.mkv', '.wmv', '.flv']
    video_files = []
    
    # Create data directory if it doesn't exist
    os.makedirs(os.path.dirname(output_csv), exist_ok=True)
    
    # Walk through the dataset directory to find all video files
    for root, dirs, files in os.walk(dataset_path):
        for file in files:
            if any(file.endswith(ext) for ext in video_extensions):
                video_files.append(os.path.join(root, file))
    
    if not video_files:
        print(f"No video files found in {dataset_path}")
        return None
    
    # Create DataFrame - determine labels based on filenames/folder structure
    data = []
    for video_path in video_files:
        video_name = os.path.basename(video_path)
        folder_name = os.path.basename(os.path.dirname(video_path))
        
        # Determine label based on filename or folder structure
        # This is a critical step - you need to figure out how to identify shoplifting videos
        if ("shoplifting" in video_name.lower() or 
            "theft" in video_name.lower() or 
            "shoplifting" in folder_name.lower() or
            "theft" in folder_name.lower()):
            label = "shoplifting"
        else:
            label = "normal"  # Or whatever the negative class is called
        
        data.append({
            "video_path": video_path,
            "video_name": video_name,
            "folder": folder_name,
            "label": label
        })
    
    # Create DataFrame and save as CSV
    df = pd.DataFrame(data)
    df.to_csv(output_csv, index=False)
    print(f"Created dataset CSV at {output_csv} with {len(df)} entries")
    print(f"Class distribution:")
    print(df["label"].value_counts())
    
    # Show some examples
    print("\nSample of created CSV:")
    print(df.head(10))
    
    return df

# Create the CSV file
dataset_path = "extracted_folder/DCSASS"  # Your dataset path
df = create_dataset_csv(dataset_path)

# If the CSV was created successfully, let's examine it
if df is not None:
    print("\n" + "="*50)
    print("DATASET ANALYSIS")
    print("="*50)
    
    # Check if we need to manually correct some labels
    print("\nChecking if manual label adjustment is needed:")
    
    # Show unique folder names
    print("\nUnique folders in dataset:")
    for folder in df['folder'].unique():
        print(f"  - {folder}")
    
    # Show unique video names (first 10)
    print("\nSample video names:")
    for video in df['video_name'].head(10):
        print(f"  - {video}")
    
    # Check if we have a good balance of classes
    shoplifting_count = len(df[df['label'] == 'shoplifting'])
    normal_count = len(df[df['label'] == 'normal'])
    
    print(f"\nClass balance:")
    print(f"Shoplifting videos: {shoplifting_count}")
    print(f"Normal videos: {normal_count}")
    
    if shoplifting_count == 0:
        print("\nWARNING: No shoplifting videos detected!")
        print("You may need to manually inspect the dataset structure and update the labeling logic.")
        print("Common approaches:")
        print("1. Check if shoplifting videos are in specific folders")
        print("2. Look for pattern in filenames (e.g., 'theft', 'steal', 'shoplift')")
        print("3. Manually review some videos to understand the dataset structure")
    
    # Save a sample of the dataset for manual inspection
    sample_df = df.head(20)[['video_name', 'folder', 'label']]
    sample_df.to_csv('data/dataset_sample_for_review.csv', index=False)
    print(f"\nSaved sample for manual review to: data/dataset_sample_for_review.csv")

Created dataset CSV at data/shoplifting.csv with 16639 entries
Class distribution:
label
normal         15743
shoplifting      896
Name: count, dtype: int64

Sample of created CSV:
                                          video_path            video_name  \
0  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...   Abuse001_x264_0.mp4
1  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...   Abuse001_x264_1.mp4
2  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_10.mp4
3  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_11.mp4
4  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_12.mp4
5  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_13.mp4
6  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_14.mp4
7  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_15.mp4
8  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_16.mp4
9  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_17.mp4

              folder   label
0  Abuse001_x264.mp4  normal
1  Abuse001_x264.mp4  normal
2  Abuse001_x264.mp4  normal
3  Abuse001_x264.mp4  normal
4  Abuse001_x264.mp4  normal
5  Abuse001_x264.mp4  normal
6  Abuse001_x264.mp4  normal
7  Abuse001_x264.mp4  normal
8  Abuse001_x264.mp4  normal
9  Abuse001_x264.mp4  normal

==================================================
DATASET ANALYSIS
==================================================

Checking if manual label adjustment is needed:

Unique folders in dataset:
  - Abuse001_x264.mp4
  - Abuse003_x264.mp4
  - Abuse004_x264.mp4
  - Abuse006_x264.mp4
  - Abuse007_x264.mp4
  - Abuse008_x264.mp4
  - Abuse010_x264.mp4
  - Abuse012_x264.mp4
  - Abuse013_x264.mp4
  - Abuse014_x264.mp4
  - Abuse016_x264.mp4
  - Abuse017_x264.mp4
  - Abuse018_x264.mp4
  - Abuse019_x264.mp4
  - Abuse020_x264.mp4
  - Abuse021_x264.mp4
  - Abuse022_x264.mp4
  - Abuse023_x264.mp4
  - Abuse024_x264.mp4
  - Abuse025_x264.mp4
  - Abuse026_x264.mp4
  - Abuse027_x264.mp4
  - Abuse028_x264.mp4
  - Abuse030_x264.mp4
  - Abuse031_x264.mp4
  - Abuse033_x264.mp4
  - Abuse034_x264.mp4
  - Abuse035_x264.mp4
  - Abuse036_x264.mp4
  - Abuse037_x264.mp4
  - Abuse039_x264.mp4
  - Abuse041_x264.mp4
  - Abuse042_x264.mp4
  - Abuse043_x264.mp4
  - Abuse044_x264.mp4
  - Abuse045_x264.mp4
  - Abuse047_x264.mp4
  - Abuse048_x264.mp4
  - Abuse050_x264.mp4
  - Arrest001_x264.mp4
  - Arrest002_x264.mp4
  - Arrest003_x264.mp4
  - Arrest004_x264.mp4
  - Arrest005_x264.mp4
  - Arrest006_x264.mp4
  - Arrest009_x264.mp4
  - Arrest011_x264.mp4
  - Arrest013_x264.mp4
  - Arrest014_x264.mp4
  - Arrest017_x264.mp4
  - Arrest019_x264.mp4
  - Arrest022_x264.mp4
  - Arrest023_x264.mp4
  - Arrest024_x264.mp4
  - Arrest025_x264.mp4
  - Arrest028_x264.mp4
  - Arrest031_x264.mp4
  - Arrest032_x264.mp4
  - Arrest036_x264.mp4
  - Arrest037_x264.mp4
  - Arrest038_x264.mp4
  - Arrest040_x264.mp4
  - Arrest041_x264.mp4
  - Arrest042_x264.mp4
  - Arrest048_x264.mp4
  - Arson002_x264.mp4
  - Arson003_x264.mp4
  - Arson005_x264.mp4
  - Arson008_x264.mp4
  - Arson011_x264.mp4
  - Arson014_x264.mp4
  - Arson016_x264.mp4
  - Arson020_x264.mp4
  - Arson023_x264.mp4
  - Arson024_x264.mp4
  - Arson027_x264.mp4
  - Arson028_x264.mp4
  - Arson029_x264.mp4
  - Arson034_x264.mp4
  - Arson036_x264.mp4
  - Arson039_x264.mp4
  - Arson040_x264.mp4
  - Arson041_x264.mp4
  - Arson042_x264.mp4
  - Arson045_x264.mp4
  - Arson047_x264.mp4
  - Arson050_x264.mp4
  - Assault002_x264.mp4
  - Assault004_x264.mp4
  - Assault005_x264.mp4
  - Assault007_x264.mp4
  - Assault009_x264.mp4
  - Assault011_x264.mp4
  - Assault013_x264.mp4
  - Assault014_x264.mp4
  - Assault015_x264.mp4
  - Assault017_x264.mp4
  - Assault019_x264.mp4
  - Assault022_x264.mp4
  - Assault025_x264.mp4
  - Assault028_x264.mp4
  - Assault030_x264.mp4
  - Assault033_x264.mp4
  - Assault034_x264.mp4
  - Assault037_x264.mp4
  - Assault040_x264.mp4
  - Assault045_x264.mp4
  - Assault047_x264.mp4
  - Assault048_x264.mp4
  - Assault049_x264.mp4
  - Burglary001_x264.mp4
  - Burglary004_x264.mp4
  - Burglary007_x264.mp4
  - Burglary009_x264.mp4
  - Burglary011_x264.mp4
  - Burglary012_x264.mp4
  - Burglary013_x264.mp4
  - Burglary014_x264.mp4
  - Burglary015_x264.mp4
  - Burglary017_x264.mp4
  - Burglary018_x264.mp4
  - Burglary019_x264.mp4
  - Burglary020_x264.mp4
  - Burglary021_x264.mp4
  - Burglary022_x264.mp4
  - Burglary023_x264.mp4
  - Burglary024_x264.mp4
  - Burglary026_x264.mp4
  - Burglary027_x264.mp4
  - Burglary034_x264.mp4
  - Burglary035_x264.mp4
  - Burglary036_x264.mp4
  - Burglary037_x264.mp4
  - Burglary041_x264.mp4
  - Burglary046_x264.mp4
  - Burglary048_x264.mp4
  - Burglary051_x264.mp4
  - Burglary053_x264.mp4
  - Burglary055_x264.mp4
  - Burglary056_x264.mp4
  - Burglary066_x264.mp4
  - Burglary069_x264.mp4
  - Burglary071_x264.mp4
  - Burglary072_x264.mp4
  - Burglary074_x264.mp4
  - Burglary077_x264.mp4
  - Burglary080_x264.mp4
  - Burglary082_x264.mp4
  - Burglary084_x264.mp4
  - Burglary085_x264.mp4
  - Burglary086_x264.mp4
  - Burglary087_x264.mp4
  - Burglary089_x264.mp4
  - Burglary090_x264.mp4
  - Burglary091_x264.mp4
  - Burglary094_x264.mp4
  - Burglary099_x264.mp4
  - Explosion004_x264.mp4
  - Explosion006_x264.mp4
  - Explosion008_x264.mp4
  - Explosion009_x264.mp4
  - Explosion011_x264.mp4
  - Explosion013_x264.mp4
  - Explosion014_x264.mp4
  - Explosion017_x264.mp4
  - Explosion020_x264.mp4
  - Explosion022_x264.mp4
  - Explosion023_x264.mp4
  - Explosion024_x264.mp4
  - Explosion026_x264.mp4
  - Explosion028_x264.mp4
  - Explosion029_x264.mp4
  - Explosion032_x264.mp4
  - Explosion033_x264.mp4
  - Explosion035_x264.mp4
  - Explosion037_x264.mp4
  - Explosion038_x264.mp4
  - Explosion042_x264.mp4
  - Explosion047_x264.mp4
  - Explosion052_x264.mp4
  - Fighting002_x264.mp4
  - Fighting003_x264.mp4
  - Fighting005_x264.mp4
  - Fighting007_x264.mp4
  - Fighting009_x264.mp4
  - Fighting012_x264.mp4
  - Fighting013_x264.mp4
  - Fighting014_x264.mp4
  - RoadAccidents001_x264.mp4
  - RoadAccidents003_x264.mp4
  - RoadAccidents006_x264.mp4
  - RoadAccidents007_x264.mp4
  - RoadAccidents008_x264.mp4
  - RoadAccidents011_x264.mp4
  - RoadAccidents013_x264.mp4
  - RoadAccidents015_x264.mp4
  - RoadAccidents016_x264.mp4
  - RoadAccidents018_x264.mp4
  - RoadAccidents019_x264.mp4
  - RoadAccidents020_x264.mp4
  - RoadAccidents023_x264.mp4
  - RoadAccidents024_x264.mp4
  - RoadAccidents025_x264.mp4
  - RoadAccidents031_x264.mp4
  - RoadAccidents032_x264.mp4
  - RoadAccidents034_x264.mp4
  - RoadAccidents036_x264.mp4
  - RoadAccidents037_x264.mp4
  - RoadAccidents048_x264.mp4
  - RoadAccidents050_x264.mp4
  - RoadAccidents057_x264.mp4
  - RoadAccidents059_x264.mp4
  - RoadAccidents064_x264.mp4
  - RoadAccidents066_x264.mp4
  - RoadAccidents067_x264.mp4
  - RoadAccidents074_x264.mp4
  - RoadAccidents076_x264.mp4
  - RoadAccidents077_x264.mp4
  - RoadAccidents079_x264.mp4
  - RoadAccidents080_x264.mp4
  - RoadAccidents082_x264.mp4
  - RoadAccidents083_x264.mp4
  - RoadAccidents088_x264.mp4
  - RoadAccidents089_x264.mp4
  - RoadAccidents090_x264.mp4
  - RoadAccidents091_x264.mp4
  - RoadAccidents092_x264.mp4
  - RoadAccidents093_x264.mp4
  - RoadAccidents094_x264.mp4
  - RoadAccidents095_x264.mp4
  - RoadAccidents098_x264.mp4
  - RoadAccidents099_x264.mp4
  - RoadAccidents103_x264.mp4
  - RoadAccidents105_x264.mp4
  - RoadAccidents106_x264.mp4
  - RoadAccidents107_x264.mp4
  - RoadAccidents109_x264.mp4
  - RoadAccidents111_x264.mp4
  - RoadAccidents113_x264.mp4
  - RoadAccidents114_x264.mp4
  - RoadAccidents115_x264.mp4
  - RoadAccidents117_x264.mp4
  - RoadAccidents118_x264.mp4
  - RoadAccidents119_x264.mp4
  - RoadAccidents120_x264.mp4
  - RoadAccidents121_x264.mp4
  - RoadAccidents123_x264.mp4
  - RoadAccidents124_x264.mp4
  - RoadAccidents125_x264.mp4
  - RoadAccidents126_x264.mp4
  - RoadAccidents127_x264.mp4
  - RoadAccidents130_x264.mp4
  - RoadAccidents131_x264.mp4
  - RoadAccidents132_x264.mp4
  - RoadAccidents135_x264.mp4
  - RoadAccidents137_x264.mp4
  - RoadAccidents138_x264.mp4
  - RoadAccidents139_x264.mp4
  - RoadAccidents140_x264.mp4
  - RoadAccidents141_x264.mp4
  - RoadAccidents145_x264.mp4
  - RoadAccidents146_x264.mp4
  - RoadAccidents149_x264.mp4
  - RoadAccidents150_x264.mp4
  - Robbery001_x264.mp4
  - Robbery002_x264.mp4
  - Robbery003_x264.mp4
  - Robbery004_x264.mp4
  - Robbery006_x264.mp4
  - Robbery007_x264.mp4
  - Robbery008_x264.mp4
  - Robbery009_x264.mp4
  - Robbery010_x264.mp4
  - Robbery013_x264.mp4
  - Robbery015_x264.mp4
  - Robbery016_x264.mp4
  - Robbery017_x264.mp4
  - Robbery018_x264.mp4
  - Robbery019_x264.mp4
  - Robbery020_x264.mp4
  - Robbery022_x264.mp4
  - Robbery023_x264.mp4
  - Robbery024_x264.mp4
  - Robbery025_x264.mp4
  - Robbery028_x264.mp4
  - Robbery029_x264.mp4
  - Robbery030_x264.mp4
  - Robbery031_x264.mp4
  - Robbery035_x264.mp4
  - Robbery036_x264.mp4
  - Robbery038_x264.mp4
  - Robbery040_x264.mp4
  - Robbery041_x264.mp4
  - Robbery042_x264.mp4
  - Robbery043_x264.mp4
  - Robbery045_x264.mp4
  - Robbery047_x264.mp4
  - Robbery048_x264.mp4
  - Robbery049_x264.mp4
  - Robbery050_x264.mp4
  - Robbery051_x264.mp4
  - Robbery052_x264.mp4
  - Robbery053_x264.mp4
  - Robbery054_x264.mp4
  - Robbery056_x264.mp4
  - Robbery057_x264.mp4
  - Robbery058_x264.mp4
  - Robbery060_x264.mp4
  - Robbery061_x264.mp4
  - Robbery062_x264.mp4
  - Robbery063_x264.mp4
  - Robbery064_x264.mp4
  - Robbery065_x264.mp4
  - Robbery066_x264.mp4
  - Robbery067_x264.mp4
  - Robbery071_x264.mp4
  - Robbery072_x264.mp4
  - Robbery077_x264.mp4
  - Robbery078_x264.mp4
  - Robbery080_x264.mp4
  - Robbery081_x264.mp4
  - Robbery082_x264.mp4
  - Robbery083_x264.mp4
  - Robbery085_x264.mp4
  - Robbery087_x264.mp4
  - Robbery088_x264.mp4
  - Robbery091_x264.mp4
  - Robbery093_x264.mp4
  - Robbery094_x264.mp4
  - Robbery095_x264.mp4
  - Robbery096_x264.mp4
  - Robbery097_x264.mp4
  - Robbery099_x264.mp4
  - Robbery100_x264.mp4
  - Robbery102_x264.mp4
  - Robbery103_x264.mp4
  - Robbery104_x264.mp4
  - Robbery105_x264.mp4
  - Robbery106_x264.mp4
  - Robbery107_x264.mp4
  - Robbery109_x264.mp4
  - Robbery110_x264.mp4
  - Robbery111_x264.mp4
  - Robbery112_x264.mp4
  - Robbery114_x264.mp4
  - Robbery115_x264.mp4
  - Robbery117_x264.mp4
  - Robbery118_x264.mp4
  - Robbery119_x264.mp4
  - Robbery120_x264.mp4
  - Robbery121_x264.mp4
  - Robbery122_x264.mp4
  - Robbery123_x264.mp4
  - Robbery126_x264.mp4
  - Robbery127_x264.mp4
  - Robbery129_x264.mp4
  - Robbery130_x264.mp4
  - Robbery131_x264.mp4
  - Robbery133_x264.mp4
  - Robbery136_x264.mp4
  - Robbery137_x264.mp4
  - Robbery139_x264.mp4
  - Robbery140_x264.mp4
  - Robbery142_x264.mp4
  - Robbery145_x264.mp4
  - Robbery146_x264.mp4
  - Robbery148_x264.mp4
  - Robbery149_x264.mp4
  - Robbery150_x264.mp4
  - Shooting002_x264.mp4
  - Shooting005_x264.mp4
  - Shooting007_x264.mp4
  - Shooting008_x264.mp4
  - Shooting009_x264.mp4
  - Shooting010_x264.mp4
  - Shooting011_x264.mp4
  - Shooting013_x264.mp4
  - Shooting015_x264.mp4
  - Shooting018_x264.mp4
  - Shooting019_x264.mp4
  - Shooting020_x264.mp4
  - Shooting021_x264.mp4
  - Shooting022_x264.mp4
  - Shooting025_x264.mp4
  - Shooting026_x264.mp4
  - Shooting028_x264.mp4
  - Shooting029_x264.mp4
  - Shooting030_x264.mp4
  - Shooting031_x264.mp4
  - Shooting033_x264.mp4
  - Shooting034_x264.mp4
  - Shooting036_x264.mp4
  - Shooting038_x264.mp4
  - Shooting041_x264.mp4
  - Shooting042_x264.mp4
  - Shooting043_x264.mp4
  - Shooting048_x264.mp4
  - Shooting050_x264.mp4
  - Shooting052_x264.mp4
  - Shoplifting001_x264.mp4
  - Shoplifting005_x264.mp4
  - Shoplifting006_x264.mp4
  - Shoplifting007_x264.mp4
  - Shoplifting009_x264.mp4
  - Shoplifting010_x264.mp4
  - Shoplifting013_x264.mp4
  - Shoplifting015_x264.mp4
  - Shoplifting016_x264.mp4
  - Shoplifting018_x264.mp4
  - Shoplifting021_x264.mp4
  - Shoplifting022_x264.mp4
  - Shoplifting024_x264.mp4
  - Shoplifting025_x264.mp4
  - Shoplifting026_x264.mp4
  - Shoplifting032_x264.mp4
  - Shoplifting036_x264.mp4
  - Shoplifting037_x264.mp4
  - Shoplifting038_x264.mp4
  - Shoplifting039_x264.mp4
  - Shoplifting042_x264.mp4
  - Shoplifting045_x264.mp4
  - Shoplifting047_x264.mp4
  - Shoplifting048_x264.mp4
  - Shoplifting049_x264.mp4
  - Shoplifting050_x264.mp4
  - Shoplifting053_x264.mp4
  - Shoplifting054_x264.mp4
  - Stealing002_x264.mp4
  - Stealing003_x264.mp4
  - Stealing006_x264.mp4
  - Stealing007_x264.mp4
  - Stealing008_x264.mp4
  - Stealing009_x264.mp4
  - Stealing010_x264.mp4
  - Stealing011_x264.mp4
  - Stealing012_x264.mp4
  - Stealing014_x264.mp4
  - Stealing015_x264.mp4
  - Stealing016_x264.mp4
  - Stealing017_x264.mp4
  - Stealing018_x264.mp4
  - Stealing021_x264.mp4
  - Stealing022_x264.mp4
  - Stealing023_x264.mp4
  - Stealing024_x264.mp4
  - Stealing026_x264.mp4
  - Stealing027_x264.mp4
  - Stealing028_x264.mp4
  - Stealing031_x264.mp4
  - Stealing036_x264.mp4
  - Stealing037_x264.mp4
  - Stealing042_x264.mp4
  - Stealing044_x264.mp4
  - Stealing047_x264.mp4
  - Stealing049_x264.mp4
  - Stealing050_x264.mp4
  - Stealing051_x264.mp4
  - Stealing052_x264.mp4
  - Stealing054_x264.mp4
  - Stealing055_x264.mp4
  - Stealing060_x264.mp4
  - Stealing061_x264.mp4
  - Stealing062_x264.mp4
  - Stealing066_x264.mp4
  - Stealing067_x264.mp4
  - Stealing070_x264.mp4
  - Stealing071_x264.mp4
  - Stealing073_x264.mp4
  - Stealing074_x264.mp4
  - Stealing075_x264.mp4
  - Stealing078_x264.mp4
  - Stealing080_x264.mp4
  - Stealing081_x264.mp4
  - Stealing082_x264.mp4
  - Stealing083_x264.mp4
  - Stealing087_x264.mp4
  - Stealing093_x264.mp4
  - Stealing094_x264.mp4
  - Stealing097_x264.mp4
  - Stealing098_x264.mp4
  - Stealing101_x264.mp4
  - Stealing102_x264.mp4
  - Stealing104_x264.mp4
  - Stealing105_x264.mp4
  - Stealing106_x264.mp4
  - Stealing107_x264.mp4
  - Stealing108_x264.mp4
  - Stealing111_x264.mp4
  - Stealing112_x264.mp4
  - Stealing113_x264.mp4
  - Stealing114_x264.mp4
  - Vandalism001_x264.mp4
  - Vandalism002_x264.mp4
  - Vandalism003_x264.mp4
  - Vandalism004_x264.mp4
  - Vandalism005_x264.mp4
  - Vandalism007_x264.mp4
  - Vandalism013_x264.mp4
  - Vandalism015_x264.mp4
  - Vandalism017_x264.mp4
  - Vandalism019_x264.mp4
  - Vandalism021_x264.mp4
  - Vandalism024_x264.mp4
  - Vandalism025_x264.mp4
  - Vandalism026_x264.mp4
  - Vandalism028_x264.mp4
  - Vandalism030_x264.mp4
  - Vandalism033_x264.mp4
  - Vandalism034_x264.mp4
  - Vandalism035_x264.mp4
  - Vandalism036_x264.mp4
  - Vandalism037_x264.mp4
  - Vandalism038_x264.mp4
  - Vandalism040_x264.mp4
  - Vandalism042_x264.mp4
  - Vandalism043_x264.mp4
  - Vandalism044_x264.mp4
  - Vandalism045_x264.mp4
  - Vandalism046_x264.mp4
  - Vandalism047_x264.mp4

Sample video names:
  - Abuse001_x264_0.mp4
  - Abuse001_x264_1.mp4
  - Abuse001_x264_10.mp4
  - Abuse001_x264_11.mp4
  - Abuse001_x264_12.mp4
  - Abuse001_x264_13.mp4
  - Abuse001_x264_14.mp4
  - Abuse001_x264_15.mp4
  - Abuse001_x264_16.mp4
  - Abuse001_x264_17.mp4

Class balance:
Shoplifting videos: 896
Normal videos: 15743

Saved sample for manual review to: data/dataset_sample_for_review.csv

In [12]:
# After running the above code, verify the CSV was created
import pandas as pd

try:
    df = pd.read_csv("data/shoplifting.csv")
    print("CSV file loaded successfully!")
    print(f"Shape: {df.shape}")
    print("\nFirst few rows:")
    print(df.head())
    
    # Now you can use this CSV file with the GitHub code
    print("\nYou can now use: df = pd.read_csv('data/shoplifting.csv')")
    
except FileNotFoundError:
    print("CSV file not found. There might have been an issue creating it.")

CSV file loaded successfully!
Shape: (16639, 4)

First few rows:
                                          video_path            video_name  \
0  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...   Abuse001_x264_0.mp4
1  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...   Abuse001_x264_1.mp4
2  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_10.mp4
3  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_11.mp4
4  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_12.mp4

              folder   label
0  Abuse001_x264.mp4  normal
1  Abuse001_x264.mp4  normal
2  Abuse001_x264.mp4  normal
3  Abuse001_x264.mp4  normal
4  Abuse001_x264.mp4  normal

You can now use: df = pd.read_csv('data/shoplifting.csv')

In [13]:
import pandas as pd
import os

# Load the created CSV
df = pd.read_csv("data/shoplifting.csv")

# Let's see how the labeling was done
print("Unique folders in the dataset:")
print(df['folder'].unique())

print("\nHow shoplifting videos were identified:")
shoplifting_df = df[df['label'] == 'shoplifting']
print("Shoplifting folders:")
print(shoplifting_df['folder'].unique())

print("\nSample shoplifting video names:")
print(shoplifting_df['video_name'].head(20).tolist())

Unique folders in the dataset:
['Abuse001_x264.mp4' 'Abuse003_x264.mp4' 'Abuse004_x264.mp4'
 'Abuse006_x264.mp4' 'Abuse007_x264.mp4' 'Abuse008_x264.mp4'
 'Abuse010_x264.mp4' 'Abuse012_x264.mp4' 'Abuse013_x264.mp4'
 'Abuse014_x264.mp4' 'Abuse016_x264.mp4' 'Abuse017_x264.mp4'
 'Abuse018_x264.mp4' 'Abuse019_x264.mp4' 'Abuse020_x264.mp4'
 'Abuse021_x264.mp4' 'Abuse022_x264.mp4' 'Abuse023_x264.mp4'
 'Abuse024_x264.mp4' 'Abuse025_x264.mp4' 'Abuse026_x264.mp4'
 'Abuse027_x264.mp4' 'Abuse028_x264.mp4' 'Abuse030_x264.mp4'
 'Abuse031_x264.mp4' 'Abuse033_x264.mp4' 'Abuse034_x264.mp4'
 'Abuse035_x264.mp4' 'Abuse036_x264.mp4' 'Abuse037_x264.mp4'
 'Abuse039_x264.mp4' 'Abuse041_x264.mp4' 'Abuse042_x264.mp4'
 'Abuse043_x264.mp4' 'Abuse044_x264.mp4' 'Abuse045_x264.mp4'
 'Abuse047_x264.mp4' 'Abuse048_x264.mp4' 'Abuse050_x264.mp4'
 'Arrest001_x264.mp4' 'Arrest002_x264.mp4' 'Arrest003_x264.mp4'
 'Arrest004_x264.mp4' 'Arrest005_x264.mp4' 'Arrest006_x264.mp4'
 'Arrest009_x264.mp4' 'Arrest011_x264.mp4' 'Arrest013_x264.mp4'
 'Arrest014_x264.mp4' 'Arrest017_x264.mp4' 'Arrest019_x264.mp4'
 'Arrest022_x264.mp4' 'Arrest023_x264.mp4' 'Arrest024_x264.mp4'
 'Arrest025_x264.mp4' 'Arrest028_x264.mp4' 'Arrest031_x264.mp4'
 'Arrest032_x264.mp4' 'Arrest036_x264.mp4' 'Arrest037_x264.mp4'
 'Arrest038_x264.mp4' 'Arrest040_x264.mp4' 'Arrest041_x264.mp4'
 'Arrest042_x264.mp4' 'Arrest048_x264.mp4' 'Arson002_x264.mp4'
 'Arson003_x264.mp4' 'Arson005_x264.mp4' 'Arson008_x264.mp4'
 'Arson011_x264.mp4' 'Arson014_x264.mp4' 'Arson016_x264.mp4'
 'Arson020_x264.mp4' 'Arson023_x264.mp4' 'Arson024_x264.mp4'
 'Arson027_x264.mp4' 'Arson028_x264.mp4' 'Arson029_x264.mp4'
 'Arson034_x264.mp4' 'Arson036_x264.mp4' 'Arson039_x264.mp4'
 'Arson040_x264.mp4' 'Arson041_x264.mp4' 'Arson042_x264.mp4'
 'Arson045_x264.mp4' 'Arson047_x264.mp4' 'Arson050_x264.mp4'
 'Assault002_x264.mp4' 'Assault004_x264.mp4' 'Assault005_x264.mp4'
 'Assault007_x264.mp4' 'Assault009_x264.mp4' 'Assault011_x264.mp4'
 'Assault013_x264.mp4' 'Assault014_x264.mp4' 'Assault015_x264.mp4'
 'Assault017_x264.mp4' 'Assault019_x264.mp4' 'Assault022_x264.mp4'
 'Assault025_x264.mp4' 'Assault028_x264.mp4' 'Assault030_x264.mp4'
 'Assault033_x264.mp4' 'Assault034_x264.mp4' 'Assault037_x264.mp4'
 'Assault040_x264.mp4' 'Assault045_x264.mp4' 'Assault047_x264.mp4'
 'Assault048_x264.mp4' 'Assault049_x264.mp4' 'Burglary001_x264.mp4'
 'Burglary004_x264.mp4' 'Burglary007_x264.mp4' 'Burglary009_x264.mp4'
 'Burglary011_x264.mp4' 'Burglary012_x264.mp4' 'Burglary013_x264.mp4'
 'Burglary014_x264.mp4' 'Burglary015_x264.mp4' 'Burglary017_x264.mp4'
 'Burglary018_x264.mp4' 'Burglary019_x264.mp4' 'Burglary020_x264.mp4'
 'Burglary021_x264.mp4' 'Burglary022_x264.mp4' 'Burglary023_x264.mp4'
 'Burglary024_x264.mp4' 'Burglary026_x264.mp4' 'Burglary027_x264.mp4'
 'Burglary034_x264.mp4' 'Burglary035_x264.mp4' 'Burglary036_x264.mp4'
 'Burglary037_x264.mp4' 'Burglary041_x264.mp4' 'Burglary046_x264.mp4'
 'Burglary048_x264.mp4' 'Burglary051_x264.mp4' 'Burglary053_x264.mp4'
 'Burglary055_x264.mp4' 'Burglary056_x264.mp4' 'Burglary066_x264.mp4'
 'Burglary069_x264.mp4' 'Burglary071_x264.mp4' 'Burglary072_x264.mp4'
 'Burglary074_x264.mp4' 'Burglary077_x264.mp4' 'Burglary080_x264.mp4'
 'Burglary082_x264.mp4' 'Burglary084_x264.mp4' 'Burglary085_x264.mp4'
 'Burglary086_x264.mp4' 'Burglary087_x264.mp4' 'Burglary089_x264.mp4'
 'Burglary090_x264.mp4' 'Burglary091_x264.mp4' 'Burglary094_x264.mp4'
 'Burglary099_x264.mp4' 'Explosion004_x264.mp4' 'Explosion006_x264.mp4'
 'Explosion008_x264.mp4' 'Explosion009_x264.mp4' 'Explosion011_x264.mp4'
 'Explosion013_x264.mp4' 'Explosion014_x264.mp4' 'Explosion017_x264.mp4'
 'Explosion020_x264.mp4' 'Explosion022_x264.mp4' 'Explosion023_x264.mp4'
 'Explosion024_x264.mp4' 'Explosion026_x264.mp4' 'Explosion028_x264.mp4'
 'Explosion029_x264.mp4' 'Explosion032_x264.mp4' 'Explosion033_x264.mp4'
 'Explosion035_x264.mp4' 'Explosion037_x264.mp4' 'Explosion038_x264.mp4'
 'Explosion042_x264.mp4' 'Explosion047_x264.mp4' 'Explosion052_x264.mp4'
 'Fighting002_x264.mp4' 'Fighting003_x264.mp4' 'Fighting005_x264.mp4'
 'Fighting007_x264.mp4' 'Fighting009_x264.mp4' 'Fighting012_x264.mp4'
 'Fighting013_x264.mp4' 'Fighting014_x264.mp4' 'RoadAccidents001_x264.mp4'
 'RoadAccidents003_x264.mp4' 'RoadAccidents006_x264.mp4'
 'RoadAccidents007_x264.mp4' 'RoadAccidents008_x264.mp4'
 'RoadAccidents011_x264.mp4' 'RoadAccidents013_x264.mp4'
 'RoadAccidents015_x264.mp4' 'RoadAccidents016_x264.mp4'
 'RoadAccidents018_x264.mp4' 'RoadAccidents019_x264.mp4'
 'RoadAccidents020_x264.mp4' 'RoadAccidents023_x264.mp4'
 'RoadAccidents024_x264.mp4' 'RoadAccidents025_x264.mp4'
 'RoadAccidents031_x264.mp4' 'RoadAccidents032_x264.mp4'
 'RoadAccidents034_x264.mp4' 'RoadAccidents036_x264.mp4'
 'RoadAccidents037_x264.mp4' 'RoadAccidents048_x264.mp4'
 'RoadAccidents050_x264.mp4' 'RoadAccidents057_x264.mp4'
 'RoadAccidents059_x264.mp4' 'RoadAccidents064_x264.mp4'
 'RoadAccidents066_x264.mp4' 'RoadAccidents067_x264.mp4'
 'RoadAccidents074_x264.mp4' 'RoadAccidents076_x264.mp4'
 'RoadAccidents077_x264.mp4' 'RoadAccidents079_x264.mp4'
 'RoadAccidents080_x264.mp4' 'RoadAccidents082_x264.mp4'
 'RoadAccidents083_x264.mp4' 'RoadAccidents088_x264.mp4'
 'RoadAccidents089_x264.mp4' 'RoadAccidents090_x264.mp4'
 'RoadAccidents091_x264.mp4' 'RoadAccidents092_x264.mp4'
 'RoadAccidents093_x264.mp4' 'RoadAccidents094_x264.mp4'
 'RoadAccidents095_x264.mp4' 'RoadAccidents098_x264.mp4'
 'RoadAccidents099_x264.mp4' 'RoadAccidents103_x264.mp4'
 'RoadAccidents105_x264.mp4' 'RoadAccidents106_x264.mp4'
 'RoadAccidents107_x264.mp4' 'RoadAccidents109_x264.mp4'
 'RoadAccidents111_x264.mp4' 'RoadAccidents113_x264.mp4'
 'RoadAccidents114_x264.mp4' 'RoadAccidents115_x264.mp4'
 'RoadAccidents117_x264.mp4' 'RoadAccidents118_x264.mp4'
 'RoadAccidents119_x264.mp4' 'RoadAccidents120_x264.mp4'
 'RoadAccidents121_x264.mp4' 'RoadAccidents123_x264.mp4'
 'RoadAccidents124_x264.mp4' 'RoadAccidents125_x264.mp4'
 'RoadAccidents126_x264.mp4' 'RoadAccidents127_x264.mp4'
 'RoadAccidents130_x264.mp4' 'RoadAccidents131_x264.mp4'
 'RoadAccidents132_x264.mp4' 'RoadAccidents135_x264.mp4'
 'RoadAccidents137_x264.mp4' 'RoadAccidents138_x264.mp4'
 'RoadAccidents139_x264.mp4' 'RoadAccidents140_x264.mp4'
 'RoadAccidents141_x264.mp4' 'RoadAccidents145_x264.mp4'
 'RoadAccidents146_x264.mp4' 'RoadAccidents149_x264.mp4'
 'RoadAccidents150_x264.mp4' 'Robbery001_x264.mp4' 'Robbery002_x264.mp4'
 'Robbery003_x264.mp4' 'Robbery004_x264.mp4' 'Robbery006_x264.mp4'
 'Robbery007_x264.mp4' 'Robbery008_x264.mp4' 'Robbery009_x264.mp4'
 'Robbery010_x264.mp4' 'Robbery013_x264.mp4' 'Robbery015_x264.mp4'
 'Robbery016_x264.mp4' 'Robbery017_x264.mp4' 'Robbery018_x264.mp4'
 'Robbery019_x264.mp4' 'Robbery020_x264.mp4' 'Robbery022_x264.mp4'
 'Robbery023_x264.mp4' 'Robbery024_x264.mp4' 'Robbery025_x264.mp4'
 'Robbery028_x264.mp4' 'Robbery029_x264.mp4' 'Robbery030_x264.mp4'
 'Robbery031_x264.mp4' 'Robbery035_x264.mp4' 'Robbery036_x264.mp4'
 'Robbery038_x264.mp4' 'Robbery040_x264.mp4' 'Robbery041_x264.mp4'
 'Robbery042_x264.mp4' 'Robbery043_x264.mp4' 'Robbery045_x264.mp4'
 'Robbery047_x264.mp4' 'Robbery048_x264.mp4' 'Robbery049_x264.mp4'
 'Robbery050_x264.mp4' 'Robbery051_x264.mp4' 'Robbery052_x264.mp4'
 'Robbery053_x264.mp4' 'Robbery054_x264.mp4' 'Robbery056_x264.mp4'
 'Robbery057_x264.mp4' 'Robbery058_x264.mp4' 'Robbery060_x264.mp4'
 'Robbery061_x264.mp4' 'Robbery062_x264.mp4' 'Robbery063_x264.mp4'
 'Robbery064_x264.mp4' 'Robbery065_x264.mp4' 'Robbery066_x264.mp4'
 'Robbery067_x264.mp4' 'Robbery071_x264.mp4' 'Robbery072_x264.mp4'
 'Robbery077_x264.mp4' 'Robbery078_x264.mp4' 'Robbery080_x264.mp4'
 'Robbery081_x264.mp4' 'Robbery082_x264.mp4' 'Robbery083_x264.mp4'
 'Robbery085_x264.mp4' 'Robbery087_x264.mp4' 'Robbery088_x264.mp4'
 'Robbery091_x264.mp4' 'Robbery093_x264.mp4' 'Robbery094_x264.mp4'
 'Robbery095_x264.mp4' 'Robbery096_x264.mp4' 'Robbery097_x264.mp4'
 'Robbery099_x264.mp4' 'Robbery100_x264.mp4' 'Robbery102_x264.mp4'
 'Robbery103_x264.mp4' 'Robbery104_x264.mp4' 'Robbery105_x264.mp4'
 'Robbery106_x264.mp4' 'Robbery107_x264.mp4' 'Robbery109_x264.mp4'
 'Robbery110_x264.mp4' 'Robbery111_x264.mp4' 'Robbery112_x264.mp4'
 'Robbery114_x264.mp4' 'Robbery115_x264.mp4' 'Robbery117_x264.mp4'
 'Robbery118_x264.mp4' 'Robbery119_x264.mp4' 'Robbery120_x264.mp4'
 'Robbery121_x264.mp4' 'Robbery122_x264.mp4' 'Robbery123_x264.mp4'
 'Robbery126_x264.mp4' 'Robbery127_x264.mp4' 'Robbery129_x264.mp4'
 'Robbery130_x264.mp4' 'Robbery131_x264.mp4' 'Robbery133_x264.mp4'
 'Robbery136_x264.mp4' 'Robbery137_x264.mp4' 'Robbery139_x264.mp4'
 'Robbery140_x264.mp4' 'Robbery142_x264.mp4' 'Robbery145_x264.mp4'
 'Robbery146_x264.mp4' 'Robbery148_x264.mp4' 'Robbery149_x264.mp4'
 'Robbery150_x264.mp4' 'Shooting002_x264.mp4' 'Shooting005_x264.mp4'
 'Shooting007_x264.mp4' 'Shooting008_x264.mp4' 'Shooting009_x264.mp4'
 'Shooting010_x264.mp4' 'Shooting011_x264.mp4' 'Shooting013_x264.mp4'
 'Shooting015_x264.mp4' 'Shooting018_x264.mp4' 'Shooting019_x264.mp4'
 'Shooting020_x264.mp4' 'Shooting021_x264.mp4' 'Shooting022_x264.mp4'
 'Shooting025_x264.mp4' 'Shooting026_x264.mp4' 'Shooting028_x264.mp4'
 'Shooting029_x264.mp4' 'Shooting030_x264.mp4' 'Shooting031_x264.mp4'
 'Shooting033_x264.mp4' 'Shooting034_x264.mp4' 'Shooting036_x264.mp4'
 'Shooting038_x264.mp4' 'Shooting041_x264.mp4' 'Shooting042_x264.mp4'
 'Shooting043_x264.mp4' 'Shooting048_x264.mp4' 'Shooting050_x264.mp4'
 'Shooting052_x264.mp4' 'Shoplifting001_x264.mp4'
 'Shoplifting005_x264.mp4' 'Shoplifting006_x264.mp4'
 'Shoplifting007_x264.mp4' 'Shoplifting009_x264.mp4'
 'Shoplifting010_x264.mp4' 'Shoplifting013_x264.mp4'
 'Shoplifting015_x264.mp4' 'Shoplifting016_x264.mp4'
 'Shoplifting018_x264.mp4' 'Shoplifting021_x264.mp4'
 'Shoplifting022_x264.mp4' 'Shoplifting024_x264.mp4'
 'Shoplifting025_x264.mp4' 'Shoplifting026_x264.mp4'
 'Shoplifting032_x264.mp4' 'Shoplifting036_x264.mp4'
 'Shoplifting037_x264.mp4' 'Shoplifting038_x264.mp4'
 'Shoplifting039_x264.mp4' 'Shoplifting042_x264.mp4'
 'Shoplifting045_x264.mp4' 'Shoplifting047_x264.mp4'
 'Shoplifting048_x264.mp4' 'Shoplifting049_x264.mp4'
 'Shoplifting050_x264.mp4' 'Shoplifting053_x264.mp4'
 'Shoplifting054_x264.mp4' 'Stealing002_x264.mp4' 'Stealing003_x264.mp4'
 'Stealing006_x264.mp4' 'Stealing007_x264.mp4' 'Stealing008_x264.mp4'
 'Stealing009_x264.mp4' 'Stealing010_x264.mp4' 'Stealing011_x264.mp4'
 'Stealing012_x264.mp4' 'Stealing014_x264.mp4' 'Stealing015_x264.mp4'
 'Stealing016_x264.mp4' 'Stealing017_x264.mp4' 'Stealing018_x264.mp4'
 'Stealing021_x264.mp4' 'Stealing022_x264.mp4' 'Stealing023_x264.mp4'
 'Stealing024_x264.mp4' 'Stealing026_x264.mp4' 'Stealing027_x264.mp4'
 'Stealing028_x264.mp4' 'Stealing031_x264.mp4' 'Stealing036_x264.mp4'
 'Stealing037_x264.mp4' 'Stealing042_x264.mp4' 'Stealing044_x264.mp4'
 'Stealing047_x264.mp4' 'Stealing049_x264.mp4' 'Stealing050_x264.mp4'
 'Stealing051_x264.mp4' 'Stealing052_x264.mp4' 'Stealing054_x264.mp4'
 'Stealing055_x264.mp4' 'Stealing060_x264.mp4' 'Stealing061_x264.mp4'
 'Stealing062_x264.mp4' 'Stealing066_x264.mp4' 'Stealing067_x264.mp4'
 'Stealing070_x264.mp4' 'Stealing071_x264.mp4' 'Stealing073_x264.mp4'
 'Stealing074_x264.mp4' 'Stealing075_x264.mp4' 'Stealing078_x264.mp4'
 'Stealing080_x264.mp4' 'Stealing081_x264.mp4' 'Stealing082_x264.mp4'
 'Stealing083_x264.mp4' 'Stealing087_x264.mp4' 'Stealing093_x264.mp4'
 'Stealing094_x264.mp4' 'Stealing097_x264.mp4' 'Stealing098_x264.mp4'
 'Stealing101_x264.mp4' 'Stealing102_x264.mp4' 'Stealing104_x264.mp4'
 'Stealing105_x264.mp4' 'Stealing106_x264.mp4' 'Stealing107_x264.mp4'
 'Stealing108_x264.mp4' 'Stealing111_x264.mp4' 'Stealing112_x264.mp4'
 'Stealing113_x264.mp4' 'Stealing114_x264.mp4' 'Vandalism001_x264.mp4'
 'Vandalism002_x264.mp4' 'Vandalism003_x264.mp4' 'Vandalism004_x264.mp4'
 'Vandalism005_x264.mp4' 'Vandalism007_x264.mp4' 'Vandalism013_x264.mp4'
 'Vandalism015_x264.mp4' 'Vandalism017_x264.mp4' 'Vandalism019_x264.mp4'
 'Vandalism021_x264.mp4' 'Vandalism024_x264.mp4' 'Vandalism025_x264.mp4'
 'Vandalism026_x264.mp4' 'Vandalism028_x264.mp4' 'Vandalism030_x264.mp4'
 'Vandalism033_x264.mp4' 'Vandalism034_x264.mp4' 'Vandalism035_x264.mp4'
 'Vandalism036_x264.mp4' 'Vandalism037_x264.mp4' 'Vandalism038_x264.mp4'
 'Vandalism040_x264.mp4' 'Vandalism042_x264.mp4' 'Vandalism043_x264.mp4'
 'Vandalism044_x264.mp4' 'Vandalism045_x264.mp4' 'Vandalism046_x264.mp4'
 'Vandalism047_x264.mp4']

How shoplifting videos were identified:
Shoplifting folders:
['Shoplifting001_x264.mp4' 'Shoplifting005_x264.mp4'
 'Shoplifting006_x264.mp4' 'Shoplifting007_x264.mp4'
 'Shoplifting009_x264.mp4' 'Shoplifting010_x264.mp4'
 'Shoplifting013_x264.mp4' 'Shoplifting015_x264.mp4'
 'Shoplifting016_x264.mp4' 'Shoplifting018_x264.mp4'
 'Shoplifting021_x264.mp4' 'Shoplifting022_x264.mp4'
 'Shoplifting024_x264.mp4' 'Shoplifting025_x264.mp4'
 'Shoplifting026_x264.mp4' 'Shoplifting032_x264.mp4'
 'Shoplifting036_x264.mp4' 'Shoplifting037_x264.mp4'
 'Shoplifting038_x264.mp4' 'Shoplifting039_x264.mp4'
 'Shoplifting042_x264.mp4' 'Shoplifting045_x264.mp4'
 'Shoplifting047_x264.mp4' 'Shoplifting048_x264.mp4'
 'Shoplifting049_x264.mp4' 'Shoplifting050_x264.mp4'
 'Shoplifting053_x264.mp4' 'Shoplifting054_x264.mp4']

Sample shoplifting video names:
['Shoplifting001_x264_0.mp4', 'Shoplifting001_x264_1.mp4', 'Shoplifting001_x264_10.mp4', 'Shoplifting001_x264_11.mp4', 'Shoplifting001_x264_12.mp4', 'Shoplifting001_x264_13.mp4', 'Shoplifting001_x264_14.mp4', 'Shoplifting001_x264_15.mp4', 'Shoplifting001_x264_16.mp4', 'Shoplifting001_x264_17.mp4', 'Shoplifting001_x264_18.mp4', 'Shoplifting001_x264_19.mp4', 'Shoplifting001_x264_2.mp4', 'Shoplifting001_x264_20.mp4', 'Shoplifting001_x264_21.mp4', 'Shoplifting001_x264_22.mp4', 'Shoplifting001_x264_23.mp4', 'Shoplifting001_x264_24.mp4', 'Shoplifting001_x264_25.mp4', 'Shoplifting001_x264_26.mp4']

In [14]:
import os

def find_data_files(directory, extensions):
    """Find files with specific extensions in a directory"""
    data_files = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            if any(file.endswith(ext) for ext in extensions):
                data_files.append(os.path.join(root, file))
    return data_files

# Search for various data file types
data_extensions = ['.csv', '.txt', '.json', '.xml', '.xlsx']
data_files = find_data_files("extracted/DCSASS", data_extensions)

if data_files:
    print("Found these data files:")
    for file in data_files:
        print(f"  - {file}")
        
    # If we found CSV files, let's examine them
    csv_files = [f for f in data_files if f.endswith('.csv')]
    if csv_files:
        print("\nLet's examine the CSV files:")
        import pandas as pd
        for csv_file in csv_files:
            try:
                df = pd.read_csv(csv_file)
                print(f"\nContents of {csv_file}:")
                print(f"Shape: {df.shape}")
                print("Columns:", df.columns.tolist())
                print("\nFirst few rows:")
                print(df.head())
            except Exception as e:
                print(f"Error reading {csv_file}: {e}")
else:
    print("No data files found. Let's check what video files are available:")
    
    # Look for video files instead
    video_extensions = ['.mp4', '.avi', '.mov', '.mkv', '.wmv']
    video_files = find_data_files("extracted_folder/DCSASS", video_extensions)
    
    if video_files:
        print(f"Found {len(video_files)} video files:")
        for video_file in video_files[:5]:  # Show first 5
            print(f"  - {video_file}")
        if len(video_files) > 5:
            print(f"  ... and {len(video_files) - 5} more")
        
        print("\nYou might need to create your own CSV file that references these videos.")
    else:
        print("No video files found either. Please check if the dataset was extracted correctly.")

No data files found. Let's check what video files are available:
Found 16639 video files:
  - extracted_folder/DCSASS\Abuse\Abuse001_x264.mp4\Abuse001_x264_0.mp4
  - extracted_folder/DCSASS\Abuse\Abuse001_x264.mp4\Abuse001_x264_1.mp4
  - extracted_folder/DCSASS\Abuse\Abuse001_x264.mp4\Abuse001_x264_10.mp4
  - extracted_folder/DCSASS\Abuse\Abuse001_x264.mp4\Abuse001_x264_11.mp4
  - extracted_folder/DCSASS\Abuse\Abuse001_x264.mp4\Abuse001_x264_12.mp4
  ... and 16634 more

You might need to create your own CSV file that references these videos.

In [15]:
# Now you can use your CSV for the next steps in the GitHub code
df = pd.read_csv("data/shoplifting.csv")

print("Dataset ready for processing!")
print(f"Total videos: {len(df)}")
print(f"Shoplifting: {len(df[df['label'] == 'shoplifting'])}")
print(f"Normal: {len(df[df['label'] == 'normal'])}")

# The GitHub code should now work with:
# df = pd.read_csv("data/shoplifting.csv")

Dataset ready for processing!
Total videos: 16639
Shoplifting: 896
Normal: 15743

In [ ]:
# Load the GitHub-style dataset
df = pd.read_csv("data/github_format_dataset.csv", index_col=0)

print("Before dropping Shoplifting column:")
print(df.head())
print(f"Shape: {df.shape}")

# This is exactly what the GitHub code does:
df.drop("Shoplifting", axis=1, inplace=True)

print("\nAfter dropping Shoplifting column:")
print(df.head())
print(f"Shape: {df.shape}")

# Now you have just the index (video names) as your features
# The GitHub code probably continues with feature extraction from these video names

Before dropping Shoplifting column:
                            Shoplifting
video_name
Shoplifting001_x264_0.mp4             1
Shoplifting001_x264_1.mp4             1
Shoplifting001_x264_10.mp4            1
Shoplifting001_x264_11.mp4            1
Shoplifting001_x264_12.mp4            1
Shape: (3584, 1)

After dropping Shoplifting column:
Empty DataFrame
Columns: []
Index: [Shoplifting001_x264_0.mp4, Shoplifting001_x264_1.mp4, Shoplifting001_x264_10.mp4, Shoplifting001_x264_11.mp4, Shoplifting001_x264_12.mp4]
Shape: (3584, 0)

In [ ]:
df.head()

Empty DataFrame
Columns: []
Index: [Shoplifting001_x264_0.mp4, Shoplifting001_x264_1.mp4, Shoplifting001_x264_10.mp4, Shoplifting001_x264_11.mp4, Shoplifting001_x264_12.mp4]

In [ ]:
import pandas as pd
import numpy as np

# Load your original dataset
df = pd.read_csv("data/shoplifting.csv")

print("Original dataset:")
print(f"Total videos: {len(df)}")
print("Current label distribution:")
print(df['label'].value_counts())

# Let's analyze the folder names to create proper categories
print("\nUnique folder names:")
for folder in sorted(df['folder'].unique()):
    print(f"  - {folder}")

# Create proper labels based on folder names
def categorize_activity(folder_name):
    folder_lower = folder_name.lower()
    
    if 'shoplift' in folder_lower or 'steal' in folder_lower:
        return 'shoplifting'
    elif 'abuse' in folder_lower:
        return 'abuse'
    elif 'arrest' in folder_lower or 'arson' in folder_lower or 'assault' in folder_lower:
        return 'suspicious'
    elif 'normal' in folder_lower or 'shopping' in folder_lower or 'customer' in folder_lower:
        return 'normal'
    else:
        return 'other'

# Apply the categorization
df['activity_type'] = df['folder'].apply(categorize_activity)

print("\nNew activity type distribution:")
print(df['activity_type'].value_counts())

# Let's see some examples
print("\nSample videos with new labels:")
sample_df = df[['video_name', 'folder', 'activity_type']].sample(10)
print(sample_df)

Original dataset:
Total videos: 33278
Current label distribution:
label
normal         31486
shoplifting     1792
Name: count, dtype: int64

Unique folder names:
  - Abuse001_x264.mp4
  - Abuse003_x264.mp4
  - Abuse004_x264.mp4
  - Abuse006_x264.mp4
  - Abuse007_x264.mp4
  - Abuse008_x264.mp4
  - Abuse010_x264.mp4
  - Abuse012_x264.mp4
  - Abuse013_x264.mp4
  - Abuse014_x264.mp4
  - Abuse016_x264.mp4
  - Abuse017_x264.mp4
  - Abuse018_x264.mp4
  - Abuse019_x264.mp4
  - Abuse020_x264.mp4
  - Abuse021_x264.mp4
  - Abuse022_x264.mp4
  - Abuse023_x264.mp4
  - Abuse024_x264.mp4
  - Abuse025_x264.mp4
  - Abuse026_x264.mp4
  - Abuse027_x264.mp4
  - Abuse028_x264.mp4
  - Abuse030_x264.mp4
  - Abuse031_x264.mp4
  - Abuse033_x264.mp4
  - Abuse034_x264.mp4
  - Abuse035_x264.mp4
  - Abuse036_x264.mp4
  - Abuse037_x264.mp4
  - Abuse039_x264.mp4
  - Abuse041_x264.mp4
  - Abuse042_x264.mp4
  - Abuse043_x264.mp4
  - Abuse044_x264.mp4
  - Abuse045_x264.mp4
  - Abuse047_x264.mp4
  - Abuse048_x264.mp4
  - Abuse050_x264.mp4
  - Arrest001_x264.mp4
  - Arrest002_x264.mp4
  - Arrest003_x264.mp4
  - Arrest004_x264.mp4
  - Arrest005_x264.mp4
  - Arrest006_x264.mp4
  - Arrest009_x264.mp4
  - Arrest011_x264.mp4
  - Arrest013_x264.mp4
  - Arrest014_x264.mp4
  - Arrest017_x264.mp4
  - Arrest019_x264.mp4
  - Arrest022_x264.mp4
  - Arrest023_x264.mp4
  - Arrest024_x264.mp4
  - Arrest025_x264.mp4
  - Arrest028_x264.mp4
  - Arrest031_x264.mp4
  - Arrest032_x264.mp4
  - Arrest036_x264.mp4
  - Arrest037_x264.mp4
  - Arrest038_x264.mp4
  - Arrest040_x264.mp4
  - Arrest041_x264.mp4
  - Arrest042_x264.mp4
  - Arrest048_x264.mp4
  - Arson002_x264.mp4
  - Arson003_x264.mp4
  - Arson005_x264.mp4
  - Arson008_x264.mp4
  - Arson011_x264.mp4
  - Arson014_x264.mp4
  - Arson016_x264.mp4
  - Arson020_x264.mp4
  - Arson023_x264.mp4
  - Arson024_x264.mp4
  - Arson027_x264.mp4
  - Arson028_x264.mp4
  - Arson029_x264.mp4
  - Arson034_x264.mp4
  - Arson036_x264.mp4
  - Arson039_x264.mp4
  - Arson040_x264.mp4
  - Arson041_x264.mp4
  - Arson042_x264.mp4
  - Arson045_x264.mp4
  - Arson047_x264.mp4
  - Arson050_x264.mp4
  - Assault002_x264.mp4
  - Assault004_x264.mp4
  - Assault005_x264.mp4
  - Assault007_x264.mp4
  - Assault009_x264.mp4
  - Assault011_x264.mp4
  - Assault013_x264.mp4
  - Assault014_x264.mp4
  - Assault015_x264.mp4
  - Assault017_x264.mp4
  - Assault019_x264.mp4
  - Assault022_x264.mp4
  - Assault025_x264.mp4
  - Assault028_x264.mp4
  - Assault030_x264.mp4
  - Assault033_x264.mp4
  - Assault034_x264.mp4
  - Assault037_x264.mp4
  - Assault040_x264.mp4
  - Assault045_x264.mp4
  - Assault047_x264.mp4
  - Assault048_x264.mp4
  - Assault049_x264.mp4
  - Burglary001_x264.mp4
  - Burglary004_x264.mp4
  - Burglary007_x264.mp4
  - Burglary009_x264.mp4
  - Burglary011_x264.mp4
  - Burglary012_x264.mp4
  - Burglary013_x264.mp4
  - Burglary014_x264.mp4
  - Burglary015_x264.mp4
  - Burglary017_x264.mp4
  - Burglary018_x264.mp4
  - Burglary019_x264.mp4
  - Burglary020_x264.mp4
  - Burglary021_x264.mp4
  - Burglary022_x264.mp4
  - Burglary023_x264.mp4
  - Burglary024_x264.mp4
  - Burglary026_x264.mp4
  - Burglary027_x264.mp4
  - Burglary034_x264.mp4
  - Burglary035_x264.mp4
  - Burglary036_x264.mp4
  - Burglary037_x264.mp4
  - Burglary041_x264.mp4
  - Burglary046_x264.mp4
  - Burglary048_x264.mp4
  - Burglary051_x264.mp4
  - Burglary053_x264.mp4
  - Burglary055_x264.mp4
  - Burglary056_x264.mp4
  - Burglary066_x264.mp4
  - Burglary069_x264.mp4
  - Burglary071_x264.mp4
  - Burglary072_x264.mp4
  - Burglary074_x264.mp4
  - Burglary077_x264.mp4
  - Burglary080_x264.mp4
  - Burglary082_x264.mp4
  - Burglary084_x264.mp4
  - Burglary085_x264.mp4
  - Burglary086_x264.mp4
  - Burglary087_x264.mp4
  - Burglary089_x264.mp4
  - Burglary090_x264.mp4
  - Burglary091_x264.mp4
  - Burglary094_x264.mp4
  - Burglary099_x264.mp4
  - Explosion004_x264.mp4
  - Explosion006_x264.mp4
  - Explosion008_x264.mp4
  - Explosion009_x264.mp4
  - Explosion011_x264.mp4
  - Explosion013_x264.mp4
  - Explosion014_x264.mp4
  - Explosion017_x264.mp4
  - Explosion020_x264.mp4
  - Explosion022_x264.mp4
  - Explosion023_x264.mp4
  - Explosion024_x264.mp4
  - Explosion026_x264.mp4
  - Explosion028_x264.mp4
  - Explosion029_x264.mp4
  - Explosion032_x264.mp4
  - Explosion033_x264.mp4
  - Explosion035_x264.mp4
  - Explosion037_x264.mp4
  - Explosion038_x264.mp4
  - Explosion042_x264.mp4
  - Explosion047_x264.mp4
  - Explosion052_x264.mp4
  - Fighting002_x264.mp4
  - Fighting003_x264.mp4
  - Fighting005_x264.mp4
  - Fighting007_x264.mp4
  - Fighting009_x264.mp4
  - Fighting012_x264.mp4
  - Fighting013_x264.mp4
  - Fighting014_x264.mp4
  - RoadAccidents001_x264.mp4
  - RoadAccidents003_x264.mp4
  - RoadAccidents006_x264.mp4
  - RoadAccidents007_x264.mp4
  - RoadAccidents008_x264.mp4
  - RoadAccidents011_x264.mp4
  - RoadAccidents013_x264.mp4
  - RoadAccidents015_x264.mp4
  - RoadAccidents016_x264.mp4
  - RoadAccidents018_x264.mp4
  - RoadAccidents019_x264.mp4
  - RoadAccidents020_x264.mp4
  - RoadAccidents023_x264.mp4
  - RoadAccidents024_x264.mp4
  - RoadAccidents025_x264.mp4
  - RoadAccidents031_x264.mp4
  - RoadAccidents032_x264.mp4
  - RoadAccidents034_x264.mp4
  - RoadAccidents036_x264.mp4
  - RoadAccidents037_x264.mp4
  - RoadAccidents048_x264.mp4
  - RoadAccidents050_x264.mp4
  - RoadAccidents057_x264.mp4
  - RoadAccidents059_x264.mp4
  - RoadAccidents064_x264.mp4
  - RoadAccidents066_x264.mp4
  - RoadAccidents067_x264.mp4
  - RoadAccidents074_x264.mp4
  - RoadAccidents076_x264.mp4
  - RoadAccidents077_x264.mp4
  - RoadAccidents079_x264.mp4
  - RoadAccidents080_x264.mp4
  - RoadAccidents082_x264.mp4
  - RoadAccidents083_x264.mp4
  - RoadAccidents088_x264.mp4
  - RoadAccidents089_x264.mp4
  - RoadAccidents090_x264.mp4
  - RoadAccidents091_x264.mp4
  - RoadAccidents092_x264.mp4
  - RoadAccidents093_x264.mp4
  - RoadAccidents094_x264.mp4
  - RoadAccidents095_x264.mp4
  - RoadAccidents098_x264.mp4
  - RoadAccidents099_x264.mp4
  - RoadAccidents103_x264.mp4
  - RoadAccidents105_x264.mp4
  - RoadAccidents106_x264.mp4
  - RoadAccidents107_x264.mp4
  - RoadAccidents109_x264.mp4
  - RoadAccidents111_x264.mp4
  - RoadAccidents113_x264.mp4
  - RoadAccidents114_x264.mp4
  - RoadAccidents115_x264.mp4
  - RoadAccidents117_x264.mp4
  - RoadAccidents118_x264.mp4
  - RoadAccidents119_x264.mp4
  - RoadAccidents120_x264.mp4
  - RoadAccidents121_x264.mp4
  - RoadAccidents123_x264.mp4
  - RoadAccidents124_x264.mp4
  - RoadAccidents125_x264.mp4
  - RoadAccidents126_x264.mp4
  - RoadAccidents127_x264.mp4
  - RoadAccidents130_x264.mp4
  - RoadAccidents131_x264.mp4
  - RoadAccidents132_x264.mp4
  - RoadAccidents135_x264.mp4
  - RoadAccidents137_x264.mp4
  - RoadAccidents138_x264.mp4
  - RoadAccidents139_x264.mp4
  - RoadAccidents140_x264.mp4
  - RoadAccidents141_x264.mp4
  - RoadAccidents145_x264.mp4
  - RoadAccidents146_x264.mp4
  - RoadAccidents149_x264.mp4
  - RoadAccidents150_x264.mp4
  - Robbery001_x264.mp4
  - Robbery002_x264.mp4
  - Robbery003_x264.mp4
  - Robbery004_x264.mp4
  - Robbery006_x264.mp4
  - Robbery007_x264.mp4
  - Robbery008_x264.mp4
  - Robbery009_x264.mp4
  - Robbery010_x264.mp4
  - Robbery013_x264.mp4
  - Robbery015_x264.mp4
  - Robbery016_x264.mp4
  - Robbery017_x264.mp4
  - Robbery018_x264.mp4
  - Robbery019_x264.mp4
  - Robbery020_x264.mp4
  - Robbery022_x264.mp4
  - Robbery023_x264.mp4
  - Robbery024_x264.mp4
  - Robbery025_x264.mp4
  - Robbery028_x264.mp4
  - Robbery029_x264.mp4
  - Robbery030_x264.mp4
  - Robbery031_x264.mp4
  - Robbery035_x264.mp4
  - Robbery036_x264.mp4
  - Robbery038_x264.mp4
  - Robbery040_x264.mp4
  - Robbery041_x264.mp4
  - Robbery042_x264.mp4
  - Robbery043_x264.mp4
  - Robbery045_x264.mp4
  - Robbery047_x264.mp4
  - Robbery048_x264.mp4
  - Robbery049_x264.mp4
  - Robbery050_x264.mp4
  - Robbery051_x264.mp4
  - Robbery052_x264.mp4
  - Robbery053_x264.mp4
  - Robbery054_x264.mp4
  - Robbery056_x264.mp4
  - Robbery057_x264.mp4
  - Robbery058_x264.mp4
  - Robbery060_x264.mp4
  - Robbery061_x264.mp4
  - Robbery062_x264.mp4
  - Robbery063_x264.mp4
  - Robbery064_x264.mp4
  - Robbery065_x264.mp4
  - Robbery066_x264.mp4
  - Robbery067_x264.mp4
  - Robbery071_x264.mp4
  - Robbery072_x264.mp4
  - Robbery077_x264.mp4
  - Robbery078_x264.mp4
  - Robbery080_x264.mp4
  - Robbery081_x264.mp4
  - Robbery082_x264.mp4
  - Robbery083_x264.mp4
  - Robbery085_x264.mp4
  - Robbery087_x264.mp4
  - Robbery088_x264.mp4
  - Robbery091_x264.mp4
  - Robbery093_x264.mp4
  - Robbery094_x264.mp4
  - Robbery095_x264.mp4
  - Robbery096_x264.mp4
  - Robbery097_x264.mp4
  - Robbery099_x264.mp4
  - Robbery100_x264.mp4
  - Robbery102_x264.mp4
  - Robbery103_x264.mp4
  - Robbery104_x264.mp4
  - Robbery105_x264.mp4
  - Robbery106_x264.mp4
  - Robbery107_x264.mp4
  - Robbery109_x264.mp4
  - Robbery110_x264.mp4
  - Robbery111_x264.mp4
  - Robbery112_x264.mp4
  - Robbery114_x264.mp4
  - Robbery115_x264.mp4
  - Robbery117_x264.mp4
  - Robbery118_x264.mp4
  - Robbery119_x264.mp4
  - Robbery120_x264.mp4
  - Robbery121_x264.mp4
  - Robbery122_x264.mp4
  - Robbery123_x264.mp4
  - Robbery126_x264.mp4
  - Robbery127_x264.mp4
  - Robbery129_x264.mp4
  - Robbery130_x264.mp4
  - Robbery131_x264.mp4
  - Robbery133_x264.mp4
  - Robbery136_x264.mp4
  - Robbery137_x264.mp4
  - Robbery139_x264.mp4
  - Robbery140_x264.mp4
  - Robbery142_x264.mp4
  - Robbery145_x264.mp4
  - Robbery146_x264.mp4
  - Robbery148_x264.mp4
  - Robbery149_x264.mp4
  - Robbery150_x264.mp4
  - Shooting002_x264.mp4
  - Shooting005_x264.mp4
  - Shooting007_x264.mp4
  - Shooting008_x264.mp4
  - Shooting009_x264.mp4
  - Shooting010_x264.mp4
  - Shooting011_x264.mp4
  - Shooting013_x264.mp4
  - Shooting015_x264.mp4
  - Shooting018_x264.mp4
  - Shooting019_x264.mp4
  - Shooting020_x264.mp4
  - Shooting021_x264.mp4
  - Shooting022_x264.mp4
  - Shooting025_x264.mp4
  - Shooting026_x264.mp4
  - Shooting028_x264.mp4
  - Shooting029_x264.mp4
  - Shooting030_x264.mp4
  - Shooting031_x264.mp4
  - Shooting033_x264.mp4
  - Shooting034_x264.mp4
  - Shooting036_x264.mp4
  - Shooting038_x264.mp4
  - Shooting041_x264.mp4
  - Shooting042_x264.mp4
  - Shooting043_x264.mp4
  - Shooting048_x264.mp4
  - Shooting050_x264.mp4
  - Shooting052_x264.mp4
  - Shoplifting001_x264.mp4
  - Shoplifting005_x264.mp4
  - Shoplifting006_x264.mp4
  - Shoplifting007_x264.mp4
  - Shoplifting009_x264.mp4
  - Shoplifting010_x264.mp4
  - Shoplifting013_x264.mp4
  - Shoplifting015_x264.mp4
  - Shoplifting016_x264.mp4
  - Shoplifting018_x264.mp4
  - Shoplifting021_x264.mp4
  - Shoplifting022_x264.mp4
  - Shoplifting024_x264.mp4
  - Shoplifting025_x264.mp4
  - Shoplifting026_x264.mp4
  - Shoplifting032_x264.mp4
  - Shoplifting036_x264.mp4
  - Shoplifting037_x264.mp4
  - Shoplifting038_x264.mp4
  - Shoplifting039_x264.mp4
  - Shoplifting042_x264.mp4
  - Shoplifting045_x264.mp4
  - Shoplifting047_x264.mp4
  - Shoplifting048_x264.mp4
  - Shoplifting049_x264.mp4
  - Shoplifting050_x264.mp4
  - Shoplifting053_x264.mp4
  - Shoplifting054_x264.mp4
  - Stealing002_x264.mp4
  - Stealing003_x264.mp4
  - Stealing006_x264.mp4
  - Stealing007_x264.mp4
  - Stealing008_x264.mp4
  - Stealing009_x264.mp4
  - Stealing010_x264.mp4
  - Stealing011_x264.mp4
  - Stealing012_x264.mp4
  - Stealing014_x264.mp4
  - Stealing015_x264.mp4
  - Stealing016_x264.mp4
  - Stealing017_x264.mp4
  - Stealing018_x264.mp4
  - Stealing021_x264.mp4
  - Stealing022_x264.mp4
  - Stealing023_x264.mp4
  - Stealing024_x264.mp4
  - Stealing026_x264.mp4
  - Stealing027_x264.mp4
  - Stealing028_x264.mp4
  - Stealing031_x264.mp4
  - Stealing036_x264.mp4
  - Stealing037_x264.mp4
  - Stealing042_x264.mp4
  - Stealing044_x264.mp4
  - Stealing047_x264.mp4
  - Stealing049_x264.mp4
  - Stealing050_x264.mp4
  - Stealing051_x264.mp4
  - Stealing052_x264.mp4
  - Stealing054_x264.mp4
  - Stealing055_x264.mp4
  - Stealing060_x264.mp4
  - Stealing061_x264.mp4
  - Stealing062_x264.mp4
  - Stealing066_x264.mp4
  - Stealing067_x264.mp4
  - Stealing070_x264.mp4
  - Stealing071_x264.mp4
  - Stealing073_x264.mp4
  - Stealing074_x264.mp4
  - Stealing075_x264.mp4
  - Stealing078_x264.mp4
  - Stealing080_x264.mp4
  - Stealing081_x264.mp4
  - Stealing082_x264.mp4
  - Stealing083_x264.mp4
  - Stealing087_x264.mp4
  - Stealing093_x264.mp4
  - Stealing094_x264.mp4
  - Stealing097_x264.mp4
  - Stealing098_x264.mp4
  - Stealing101_x264.mp4
  - Stealing102_x264.mp4
  - Stealing104_x264.mp4
  - Stealing105_x264.mp4
  - Stealing106_x264.mp4
  - Stealing107_x264.mp4
  - Stealing108_x264.mp4
  - Stealing111_x264.mp4
  - Stealing112_x264.mp4
  - Stealing113_x264.mp4
  - Stealing114_x264.mp4
  - Vandalism001_x264.mp4
  - Vandalism002_x264.mp4
  - Vandalism003_x264.mp4
  - Vandalism004_x264.mp4
  - Vandalism005_x264.mp4
  - Vandalism007_x264.mp4
  - Vandalism013_x264.mp4
  - Vandalism015_x264.mp4
  - Vandalism017_x264.mp4
  - Vandalism019_x264.mp4
  - Vandalism021_x264.mp4
  - Vandalism024_x264.mp4
  - Vandalism025_x264.mp4
  - Vandalism026_x264.mp4
  - Vandalism028_x264.mp4
  - Vandalism030_x264.mp4
  - Vandalism033_x264.mp4
  - Vandalism034_x264.mp4
  - Vandalism035_x264.mp4
  - Vandalism036_x264.mp4
  - Vandalism037_x264.mp4
  - Vandalism038_x264.mp4
  - Vandalism040_x264.mp4
  - Vandalism042_x264.mp4
  - Vandalism043_x264.mp4
  - Vandalism044_x264.mp4
  - Vandalism045_x264.mp4
  - Vandalism046_x264.mp4
  - Vandalism047_x264.mp4

New activity type distribution:
activity_type
other          20350
shoplifting     5888
suspicious      4544
abuse           2496
Name: count, dtype: int64

Sample videos with new labels:
                         video_name                     folder activity_type
17356       Shooting028_x264_20.mp4       Shooting028_x264.mp4         other
24687  RoadAccidents130_x264_23.mp4  RoadAccidents130_x264.mp4         other
21488      Vandalism042_x264_24.mp4      Vandalism042_x264.mp4         other
6536          Arrest013_x264_16.mp4         Arrest013_x264.mp4    suspicious
31363       Stealing060_x264_13.mp4       Stealing060_x264.mp4   shoplifting
12596  RoadAccidents109_x264_27.mp4  RoadAccidents109_x264.mp4         other
28266         Robbery142_x264_2.mp4        Robbery142_x264.mp4         other
31294        Stealing054_x264_0.mp4       Stealing054_x264.mp4   shoplifting
24434  RoadAccidents119_x264_26.mp4  RoadAccidents119_x264.mp4         other
24086   RoadAccidents103_x264_3.mp4  RoadAccidents103_x264.mp4         other

In [ ]:
import pandas as pd
import os

# Load your dataset
df = pd.read_csv("data/shoplifting.csv")  # or your current DataFrame

print("Your current DataFrame structure:")
print(df.head())
print(f"Shape: {df.shape}")

# Transform to GitHub format
# 1. Create the full video paths in the format GitHub expects
def create_github_path(row):
    """Create path in format: data/Shoplifting/Shoplifting001_x264_0.mp4"""
    # Extract the base category (Shoplifting, Abuse, etc.)
    category = row['folder'].split('_')[0]  # Gets "Shoplifting" from "Shoplifting001_x264.mp4"
    
    # Create the path GitHub wants
    return f"data/{category}/{row['video_name']}"

# Apply the path transformation
df['github_path'] = df.apply(create_github_path, axis=1)

# 2. Create binary labels (1 for shoplifting, 0 for everything else)
df['github_label'] = (df['activity_type'] == 'shoplifting').astype(int)

# 3. Create the GitHub-style DataFrame
github_df = pd.DataFrame({
    'video_path': df['github_path'],
    'label': df['github_label']
})

print("\nTransformed to GitHub format:")
print(github_df.head())
print(f"New shape: {github_df.shape}")

# 4. Save in GitHub format
github_df.to_csv("data/github_format_dataset.csv", index=False)
print("\nSaved GitHub format dataset to: data/github_format_dataset.csv")

Your current DataFrame structure:
                                          video_path            video_name  \
0  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...   Abuse001_x264_0.mp4
1  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...   Abuse001_x264_1.mp4
2  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_10.mp4
3  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_11.mp4
4  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_12.mp4

              folder   label
0  Abuse001_x264.mp4  normal
1  Abuse001_x264.mp4  normal
2  Abuse001_x264.mp4  normal
3  Abuse001_x264.mp4  normal
4  Abuse001_x264.mp4  normal
Shape: (33278, 4)

KeyError: 'activity_type'

In [ ]:
import pandas as pd
import os

# Load your dataset
df = pd.read_csv("data/shoplifting.csv")  # or your current DataFrame

print("Your current DataFrame structure:")
print(df.head())
print(f"Shape: {df.shape}")

# Step 1: First, let's see what columns you actually have
print("\nColumns in your DataFrame:")
print(df.columns.tolist())

# Step 2: Create the activity_type column if it doesn't exist
if 'activity_type' not in df.columns:
    print("\nCreating activity_type column...")
    def categorize_activity(folder_name):
        folder_lower = folder_name.lower()
        
        if 'shoplift' in folder_lower or 'steal' in folder_lower:
            return 'shoplifting'
        elif 'abuse' in folder_lower:
            return 'abuse'
        elif 'arrest' in folder_lower or 'arson' in folder_lower or 'assault' in folder_lower:
            return 'suspicious'
        elif 'normal' in folder_lower or 'shopping' in folder_lower or 'customer' in folder_lower:
            return 'normal'
        else:
            return 'other'
    
    df['activity_type'] = df['folder'].apply(categorize_activity)

# Step 3: Create the github_path column
print("\nCreating github_path column...")
def create_github_path(row):
    """Create path in format: data/Shoplifting_filtered/Shoplifting001_x264_0.mp4"""
    # Extract the base category (Shoplifting, Abuse, etc.)
    category = row['folder'].split('_')[0]  # Gets "Shoplifting" from "Shoplifting001_x264.mp4"
    
    # Create the path GitHub wants
    return f"data/{category}/{row['video_name']}"

df['github_path'] = df.apply(create_github_path, axis=1)

# Step 4: Create the github_label column (binary: 1 for shoplifting, 0 for everything else)
print("Creating github_label column...")
df['github_label'] = (df['activity_type'] == 'shoplifting').astype(int)

# Step 5: Now create the GitHub-style DataFrame
print("Creating GitHub format DataFrame...")
github_df = pd.DataFrame({
    'video_path': df['github_path'],
    'label': df['github_label']
})

print("\nTransformed to GitHub format:")
print(github_df.head())
print(f"New shape: {github_df.shape}")

# Step 6: Save in GitHub format
github_df.to_csv("data/github_format_dataset.csv", index=False)
print("\nSaved GitHub format dataset to: data/github_format_dataset.csv")

# Step 7: Create EXACT replica of GitHub format (no column names)
github_exact = pd.DataFrame({
    '': df['github_path'],  # Empty column name for first column
    ' ': df['github_label']  # Space as column name for second column
})

print("\nEXACT GitHub format replica:")
print(github_exact.head())

# Save without column names
github_exact.to_csv("data/github_exact_format.csv", header=False, index=False)
print("Saved exact GitHub format to: data/github_exact_format.csv")

Your current DataFrame structure:
                                          video_path            video_name  \
0  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...   Abuse001_x264_0.mp4
1  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...   Abuse001_x264_1.mp4
2  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_10.mp4
3  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_11.mp4
4  extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...  Abuse001_x264_12.mp4

              folder   label
0  Abuse001_x264.mp4  normal
1  Abuse001_x264.mp4  normal
2  Abuse001_x264.mp4  normal
3  Abuse001_x264.mp4  normal
4  Abuse001_x264.mp4  normal
Shape: (33278, 4)

Columns in your DataFrame:
['video_path', 'video_name', 'folder', 'label']

Creating activity_type column...

Creating github_path column...
Creating github_label column...
Creating GitHub format DataFrame...

Transformed to GitHub format:
                           video_path  label
0   data/Abuse001/Abuse001_x264_0.mp4      0
1   data/Abuse001/Abuse001_x264_1.mp4      0
2  data/Abuse001/Abuse001_x264_10.mp4      0
3  data/Abuse001/Abuse001_x264_11.mp4      0
4  data/Abuse001/Abuse001_x264_12.mp4      0
New shape: (33278, 2)

Saved GitHub format dataset to: data/github_format_dataset.csv

EXACT GitHub format replica:

0   data/Abuse001/Abuse001_x264_0.mp4  0
1   data/Abuse001/Abuse001_x264_1.mp4  0
2  data/Abuse001/Abuse001_x264_10.mp4  0
3  data/Abuse001/Abuse001_x264_11.mp4  0
4  data/Abuse001/Abuse001_x264_12.mp4  0
Saved exact GitHub format to: data/github_exact_format.csv

In [ ]:
# Pivot your DataFrame to have video names as columns
pivoted_df = df.pivot(columns='video_name', values='video_path')
print("Pivoted DataFrame (video names as columns):")
print(pivoted_df.head())

# Now you could theoretically do something like:
# for col in pivoted_df.columns:
#     pivoted_df[col] = pivoted_df[col].apply(lambda x: "data/github_format_dataset/" + os.path.basename(x))

Pivoted DataFrame (video names as columns):
video_name                                Abuse001_x264_0.mp4  \
0           extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...
1                                                         NaN
2                                                         NaN
3                                                         NaN
4                                                         NaN

video_name                                Abuse001_x264_1.mp4  \
0                                                         NaN
1           extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...
2                                                         NaN
3                                                         NaN
4                                                         NaN

video_name                               Abuse001_x264_10.mp4  \
0                                                         NaN
1                                                         NaN
2           extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...
3                                                         NaN
4                                                         NaN

video_name                               Abuse001_x264_11.mp4  \
0                                                         NaN
1                                                         NaN
2                                                         NaN
3           extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...
4                                                         NaN

video_name                               Abuse001_x264_12.mp4  \
0                                                         NaN
1                                                         NaN
2                                                         NaN
3                                                         NaN
4           extracted_folder/DCSASS\Abuse\Abuse001_x264.mp...

video_name Abuse001_x264_13.mp4 Abuse001_x264_14.mp4 Abuse001_x264_15.mp4  \
0                           NaN                  NaN                  NaN
1                           NaN                  NaN                  NaN
2                           NaN                  NaN                  NaN
3                           NaN                  NaN                  NaN
4                           NaN                  NaN                  NaN

video_name Abuse001_x264_16.mp4 Abuse001_x264_17.mp4  ...  \
0                           NaN                  NaN  ...
1                           NaN                  NaN  ...
2                           NaN                  NaN  ...
3                           NaN                  NaN  ...
4                           NaN                  NaN  ...

video_name Vandalism047_x264_29.mp4 Vandalism047_x264_3.mp4  \
0                               NaN                     NaN
1                               NaN                     NaN
2                               NaN                     NaN
3                               NaN                     NaN
4                               NaN                     NaN

video_name Vandalism047_x264_30.mp4 Vandalism047_x264_31.mp4  \
0                               NaN                      NaN
1                               NaN                      NaN
2                               NaN                      NaN
3                               NaN                      NaN
4                               NaN                      NaN

video_name Vandalism047_x264_4.mp4 Vandalism047_x264_5.mp4  \
0                              NaN                     NaN
1                              NaN                     NaN
2                              NaN                     NaN
3                              NaN                     NaN
4                              NaN                     NaN

video_name Vandalism047_x264_6.mp4 Vandalism047_x264_7.mp4  \
0                              NaN                     NaN
1                              NaN                     NaN
2                              NaN                     NaN
3                              NaN                     NaN
4                              NaN                     NaN

video_name Vandalism047_x264_8.mp4 Vandalism047_x264_9.mp4
0                              NaN                     NaN
1                              NaN                     NaN
2                              NaN                     NaN
3                              NaN                     NaN
4                              NaN                     NaN

[5 rows x 16639 columns]

In [ ]:
# Modify the video_path column to match GitHub format
df['video_path'] = df['video_path'].apply(lambda x: "data/github_format_dataset/" + os.path.basename(x))

print("Updated video paths:")
print(df[['video_name', 'video_path']].head())

Updated video paths:
             video_name                                       video_path
0   Abuse001_x264_0.mp4   data/github_format_dataset/Abuse001_x264_0.mp4
1   Abuse001_x264_1.mp4   data/github_format_dataset/Abuse001_x264_1.mp4
2  Abuse001_x264_10.mp4  data/github_format_dataset/Abuse001_x264_10.mp4
3  Abuse001_x264_11.mp4  data/github_format_dataset/Abuse001_x264_11.mp4
4  Abuse001_x264_12.mp4  data/github_format_dataset/Abuse001_x264_12.mp4

In [ ]:
df.head()

,video_path,video_name,folder,label,activity_type,github_path,github_label
0,data/github_format_dataset/Abuse001_x264_0.mp4,Abuse001_x264_0.mp4,Abuse001_x264.mp4,normal,abuse,data/Abuse001/Abuse001_x264_0.mp4,0
1,data/github_format_dataset/Abuse001_x264_1.mp4,Abuse001_x264_1.mp4,Abuse001_x264.mp4,normal,abuse,data/Abuse001/Abuse001_x264_1.mp4,0
2,data/github_format_dataset/Abuse001_x264_10.mp4,Abuse001_x264_10.mp4,Abuse001_x264.mp4,normal,abuse,data/Abuse001/Abuse001_x264_10.mp4,0
3,data/github_format_dataset/Abuse001_x264_11.mp4,Abuse001_x264_11.mp4,Abuse001_x264.mp4,normal,abuse,data/Abuse001/Abuse001_x264_11.mp4,0
4,data/github_format_dataset/Abuse001_x264_12.mp4,Abuse001_x264_12.mp4,Abuse001_x264.mp4,normal,abuse,data/Abuse001/Abuse001_x264_12.mp4,0

In [ ]:
df = df.rename(columns={'Shoplifting001_x264_0': 'path', '0': 'target'})

In [ ]:
import os

def explore_file_structure():
    """Explore your actual file structure to understand the correct paths"""
    base_path = "extracted_folder"
    
    if not os.path.exists(base_path):
        print(f"❌ Base path '{base_path}' does not exist!")
        return False
    
    print("📁 Exploring file structure:")
    
    # Check DCSASS directory
    dcsass_path = os.path.join(base_path, "DCSASS")
    if not os.path.exists(dcsass_path):
        print(f"❌ DCSASS directory not found at: {dcsass_path}")
        print("Available directories in extracted_folder:")
        for item in os.listdir(base_path):
            print(f"  - {item}")
        return False
    
    print("✅ Found DCSASS directory")
    
    # Explore DCSASS contents
    print("\n📁 Contents of DCSASS:")
    for category in os.listdir(dcsass_path):
        category_path = os.path.join(dcsass_path, category)
        if os.path.isdir(category_path):
            print(f"  📁 {category}/")
            # Show first few items
            try:
                items = os.listdir(category_path)
                for item in items[:3]:  # Show first 3
                    item_path = os.path.join(category_path, item)
                    print(f"    - {item} ({'dir' if os.path.isdir(item_path) else 'file'})")
                if len(items) > 3:
                    print(f"    - ... and {len(items) - 3} more")
            except PermissionError:
                print("    🚫 Permission denied")
    
    return True

# Run the exploration
explore_file_structure()

📁 Exploring file structure:
✅ Found DCSASS directory

📁 Contents of DCSASS:
  📁 Abuse/
    - Abuse001_x264.mp4 (dir)
    - Abuse003_x264.mp4 (dir)
    - Abuse004_x264.mp4 (dir)
    - ... and 36 more
  📁 Arrest/
    - Arrest001_x264.mp4 (dir)
    - Arrest002_x264.mp4 (dir)
    - Arrest003_x264.mp4 (dir)
    - ... and 23 more
  📁 Arson/
    - Arson002_x264.mp4 (dir)
    - Arson003_x264.mp4 (dir)
    - Arson005_x264.mp4 (dir)
    - ... and 19 more
  📁 Assault/
    - Assault002_x264.mp4 (dir)
    - Assault004_x264.mp4 (dir)
    - Assault005_x264.mp4 (dir)
    - ... and 20 more
  📁 Burglary/
    - Burglary001_x264.mp4 (dir)
    - Burglary004_x264.mp4 (dir)
    - Burglary007_x264.mp4 (dir)
    - ... and 44 more
  📁 Explosion/
    - Explosion004_x264.mp4 (dir)
    - Explosion006_x264.mp4 (dir)
    - Explosion008_x264.mp4 (dir)
    - ... and 20 more
  📁 Fighting/
    - Fighting002_x264.mp4 (dir)
    - Fighting003_x264.mp4 (dir)
    - Fighting005_x264.mp4 (dir)
    - ... and 5 more
  📁 Labels/
    - Abuse.csv (file)
    - Arrest.csv (file)
    - Arson.csv (file)
    - ... and 10 more
  📁 RoadAccidents/
    - RoadAccidents001_x264.mp4 (dir)
    - RoadAccidents003_x264.mp4 (dir)
    - RoadAccidents006_x264.mp4 (dir)
    - ... and 73 more
  📁 Robbery/
    - Robbery001_x264.mp4 (dir)
    - Robbery002_x264.mp4 (dir)
    - Robbery003_x264.mp4 (dir)
    - ... and 102 more
  📁 Shooting/
    - Shooting002_x264.mp4 (dir)
    - Shooting005_x264.mp4 (dir)
    - Shooting007_x264.mp4 (dir)
    - ... and 27 more
  📁 Shoplifting/
    - Shoplifting001_x264.mp4 (dir)
    - Shoplifting005_x264.mp4 (dir)
    - Shoplifting006_x264.mp4 (dir)
    - ... and 25 more
  📁 Stealing/
    - Stealing002_x264.mp4 (dir)
    - Stealing003_x264.mp4 (dir)
    - Stealing006_x264.mp4 (dir)
    - ... and 61 more
  📁 Vandalism/
    - Vandalism001_x264.mp4 (dir)
    - Vandalism002_x264.mp4 (dir)
    - Vandalism003_x264.mp4 (dir)
    - ... and 26 more

True

In [ ]:
df.head()

,video_path,video_name,folder,label,activity_type,github_path,github_label
0,data/github_format_dataset/Abuse001_x264_0.mp4,Abuse001_x264_0.mp4,Abuse001_x264.mp4,normal,abuse,data/Abuse001/Abuse001_x264_0.mp4,0
1,data/github_format_dataset/Abuse001_x264_1.mp4,Abuse001_x264_1.mp4,Abuse001_x264.mp4,normal,abuse,data/Abuse001/Abuse001_x264_1.mp4,0
2,data/github_format_dataset/Abuse001_x264_10.mp4,Abuse001_x264_10.mp4,Abuse001_x264.mp4,normal,abuse,data/Abuse001/Abuse001_x264_10.mp4,0
3,data/github_format_dataset/Abuse001_x264_11.mp4,Abuse001_x264_11.mp4,Abuse001_x264.mp4,normal,abuse,data/Abuse001/Abuse001_x264_11.mp4,0
4,data/github_format_dataset/Abuse001_x264_12.mp4,Abuse001_x264_12.mp4,Abuse001_x264.mp4,normal,abuse,data/Abuse001/Abuse001_x264_12.mp4,0

In [ ]:
import os
import cv2
import pandas as pd

def extract_frames_smart(video_path, target, output_dir, video_index, max_frames_per_video=50):
    """Extract frames efficiently with limits"""
    frame_count = 0
    cap = cv2.VideoCapture(video_path)
    
    if not cap.isOpened():
        print(f"Warning: Could not open video {video_path}")
        return frame_count

    # Create output directory
    frame_dir = os.path.join(output_dir, "normal" if target == 0 else "abnormal")
    os.makedirs(frame_dir, exist_ok=True)

    # Get total frames and calculate sampling rate
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if total_frames > max_frames_per_video:
        frame_interval = max(1, total_frames // max_frames_per_video)
    else:
        frame_interval = 1

    # Extract frames with sampling
    current_frame = 0
    while cap.isOpened() and frame_count < max_frames_per_video:
        ret, frame = cap.read()
        if not ret:
            break
            
        if current_frame % frame_interval == 0:
            cv2.imwrite(os.path.join(frame_dir, f"video_{video_index}_frame_{frame_count}.jpg"), frame)
            frame_count += 1
            
        current_frame += 1

    cap.release()
    return frame_count

# Process in batches to avoid overwhelming the system
def process_batch(df, start_idx, end_idx, output_dir):
    """Process a batch of videos"""
    for index in range(start_idx, end_idx):
        if index >= len(df):
            break
            
        row = df.iloc[index]
        video_path = row['actual_video_path'].strip()
        target = row['label']
        
        print(f"Processing {index+1}/{len(df)}: {os.path.basename(video_path)}")
        extract_frames_smart(video_path, target, output_dir, index)

In [ ]:
df.head()

                           video_path  label
0   data/Abuse001/Abuse001_x264_0.mp4      0
1   data/Abuse001/Abuse001_x264_1.mp4      0
2  data/Abuse001/Abuse001_x264_10.mp4      0
3  data/Abuse001/Abuse001_x264_11.mp4      0
4  data/Abuse001/Abuse001_x264_12.mp4      0

In [3]:
import os
import random
import shutil

# Define the paths
output_normal_dir = "output/normal"
test_normal_dir = "test/normal"

# Create the test/normal directory if it doesn't exist
if not os.path.exists(test_normal_dir):
    os.makedirs(test_normal_dir)

# Create the output/normal directory if it doesn't exist
if not os.path.exists(output_normal_dir):
    os.makedirs(output_normal_dir)

# List all files in the output/normal directory
files = os.listdir(output_normal_dir)

# Calculate the number of files to move (20%)
num_files_to_move = int(0.2 * len(files))

# Randomly select files to move
files_to_move = random.sample(files, num_files_to_move)

# Move the selected files to the test/normal directory
for file_name in files_to_move:
    src = os.path.join(output_normal_dir, file_name)
    dst = os.path.join(test_normal_dir, file_name)
    shutil.move(src, dst)

print("Images moved to the test/normal directory.")

Images moved to the test/normal directory.

# Image Feature Extraction

This section implements feature extraction for the frame images:
1. Load pre-trained VGG16 model
2. Process both normal and abnormal images
3. Save features for training and testing sets separately

In [ ]:
import os
import numpy as np
from tensorflow.keras.applications import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.preprocessing import image
from sklearn.preprocessing import StandardScaler
from tqdm.notebook import tqdm

def extract_image_features(img_path, model):
    """
    Extract features from a single image using VGG16
    """
    try:
        # Load and preprocess image
        img = image.load_img(img_path, target_size=(224, 224))
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        x = preprocess_input(x)
        
        # Extract features
        features = model.predict(x, verbose=0)
        return features.flatten()
    
    except Exception as e:
        print(f"Error processing image {img_path}: {str(e)}")
        return None

def process_directory(directory, model):
    """
    Extract features from all images in a directory
    """
    features_list = []
    file_paths = []
    
    # Get all image files
    image_files = [f for f in os.listdir(directory) if f.endswith(('.jpg', '.jpeg', '.png'))]
    
    # Process each image with progress bar
    for img_file in tqdm(image_files, desc=f"Processing {os.path.basename(directory)}"):
        img_path = os.path.join(directory, img_file)
        features = extract_image_features(img_path, model)
        
        if features is not None:
            features_list.append(features)
            file_paths.append(img_path)
    
    return np.array(features_list), file_paths

# Dataset Organization and Feature Extraction

Given the DCSASS dataset structure with categories like:
- Shoplifting (target class)
- Abuse, Arrest, Arson, Assault, etc. (non-target classes)

We'll organize the data and extract features in the following steps:
1. Organize videos into binary classes (shoplifting vs non-shoplifting)
2. Extract frames from videos
3. Apply VGG16 for feature extraction
4. Save processed features for training

In [17]:
import os

def explore_video_directories():
    """Explore what's inside the video directories"""
    base_path = "extracted_folder/DCSASS"
    
    print("🔍 Exploring video directories:")
    
    # Check a few video directories to see what's inside
    sample_categories = ['Abuse', 'Shoplifting']  # Check these categories
    
    for category in sample_categories:
        category_path = os.path.join(base_path, category)
        if os.path.exists(category_path):
            print(f"\n📁 {category}/:")
            video_dirs = os.listdir(category_path)
            
            for video_dir in video_dirs[:3]:  # Check first 3 videos
                video_dir_path = os.path.join(category_path, video_dir)
                if os.path.isdir(video_dir_path):
                    print(f"  📁 {video_dir}/")
                    # Show contents of this video directory
                    try:
                        contents = os.listdir(video_dir_path)
                        for item in contents[:5]:  # Show first 5 items
                            print(f"    - {item}")
                        if len(contents) > 5:
                            print(f"    - ... and {len(contents) - 5} more")
                    except PermissionError:
                        print("    🚫 Permission denied")
                else:
                    print(f"  📄 {video_dir} (file)")
        else:
            print(f"❌ Category '{category}' not found")

# Explore what's inside the video directories
explore_video_directories()

🔍 Exploring video directories:

📁 Abuse/:
  📁 Abuse001_x264.mp4/
    - Abuse001_x264_0.mp4
    - Abuse001_x264_1.mp4
    - Abuse001_x264_10.mp4
    - Abuse001_x264_11.mp4
    - Abuse001_x264_12.mp4
    - ... and 27 more
  📁 Abuse003_x264.mp4/
    - Abuse003_x264_0.mp4
    - Abuse003_x264_1.mp4
    - Abuse003_x264_10.mp4
    - Abuse003_x264_11.mp4
    - Abuse003_x264_12.mp4
    - ... and 27 more
  📁 Abuse004_x264.mp4/
    - Abuse004_x264_0.mp4
    - Abuse004_x264_1.mp4
    - Abuse004_x264_10.mp4
    - Abuse004_x264_11.mp4
    - Abuse004_x264_12.mp4
    - ... and 27 more

📁 Shoplifting/:
  📁 Shoplifting001_x264.mp4/
    - Shoplifting001_x264_0.mp4
    - Shoplifting001_x264_1.mp4
    - Shoplifting001_x264_10.mp4
    - Shoplifting001_x264_11.mp4
    - Shoplifting001_x264_12.mp4
    - ... and 27 more
  📁 Shoplifting005_x264.mp4/
    - Shoplifting005_x264_0.mp4
    - Shoplifting005_x264_1.mp4
    - Shoplifting005_x264_10.mp4
    - Shoplifting005_x264_11.mp4
    - Shoplifting005_x264_12.mp4
    - ... and 27 more
  📁 Shoplifting006_x264.mp4/
    - Shoplifting006_x264_0.mp4
    - Shoplifting006_x264_1.mp4
    - Shoplifting006_x264_10.mp4
    - Shoplifting006_x264_11.mp4
    - Shoplifting006_x264_12.mp4
    - ... and 27 more

In [11]:
def organize_dataset(base_path="extracted_folder/DCSASS"):
    """
    Organize the DCSASS dataset into shoplifting and non-shoplifting categories
    """
    categories = {}
    shoplifting_videos = []
    normal_videos = []
    
    # Scan through all categories
    for category in os.listdir(base_path):
        category_path = os.path.join(base_path, category)
        if os.path.isdir(category_path):
            # Initialize category counter
            categories[category] = 0
            
            # Scan through video directories
            for video_dir in os.listdir(category_path):
                video_dir_path = os.path.join(category_path, video_dir)
                if os.path.isdir(video_dir_path):
                    # Look for videos inside each directory
                    video_files = [f for f in os.listdir(video_dir_path) 
                                 if f.endswith(('.mp4', '.avi'))]
                    
                    if video_files:
                        categories[category] += 1
                        # Get the first video file (there should be only one)
                        video_path = os.path.join(video_dir_path, video_files[0])
                        
                        # Classify video
                        if category.lower() in ['shoplifting', 'stealing', 'theft']:
                            shoplifting_videos.append(video_path)
                        else:
                            normal_videos.append(video_path)
    
    print("Dataset Statistics:")
    print("------------------")
    for category, count in categories.items():
        print(f"{category}: {count} videos")
    
    print(f"\nTotal Shoplifting videos: {len(shoplifting_videos)}")
    print(f"Total Normal videos: {len(normal_videos)}")
    
    return shoplifting_videos, normal_videos

In [12]:
def extract_frames_from_videos(video_paths, output_dir, label, frames_per_video=30):
    """
    Extract frames from a list of videos
    """
    os.makedirs(output_dir, exist_ok=True)
    
    for i, video_path in enumerate(tqdm(video_paths, desc=f"Processing {label} videos")):
        try:
            # Verify video file exists
            if not os.path.exists(video_path):
                print(f"Video file not found: {video_path}")
                continue
            
            # Try to open the video
            cap = cv2.VideoCapture(str(video_path))
            if not cap.isOpened():
                print(f"Failed to open video: {video_path}")
                print("Make sure the video file is valid and not corrupted")
                continue
            
            # Get total frames and calculate sampling interval
            total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
            if total_frames <= 0:
                print(f"No frames found in video: {video_path}")
                continue
                
            frame_interval = max(1, total_frames // frames_per_video)
            
            frame_count = 0
            current_frame = 0
            
            while cap.isOpened() and frame_count < frames_per_video:
                ret, frame = cap.read()
                if not ret:
                    break
                    
                if current_frame % frame_interval == 0:
                    # Create a unique frame name using video directory name
                    video_dir = os.path.basename(os.path.dirname(video_path))
                    frame_path = os.path.join(output_dir, 
                                            f"{label}_{video_dir}_frame_{frame_count:03d}.jpg")
                    
                    # Save frame with error checking
                    try:
                        cv2.imwrite(frame_path, frame)
                        frame_count += 1
                    except Exception as e:
                        print(f"Error saving frame from {video_path}: {str(e)}")
                
                current_frame += 1
            
            cap.release()
            
            if frame_count == 0:
                print(f"Warning: No frames were extracted from {video_path}")
            else:
                print(f"Successfully extracted {frame_count} frames from {video_path}")
            
        except Exception as e:
            print(f"Error processing video {video_path}: {str(e)}")
            continue
            
    return output_dir

In [13]:
import os
import cv2
import random
import numpy as np
from tqdm import tqdm

# 1. Organize dataset
print("Organizing dataset...")
shoplifting_videos, normal_videos = organize_dataset()

# 2. Create output directories
output_base = "processed_frames"
train_shop_dir = os.path.join(output_base, "train", "shoplifting")
train_normal_dir = os.path.join(output_base, "train", "normal")
test_shop_dir = os.path.join(output_base, "test", "shoplifting")
test_normal_dir = os.path.join(output_base, "test", "normal")

# 3. Split data into train and test
test_ratio = 0.2
random.seed(42)  # For reproducibility

test_shop = random.sample(shoplifting_videos, int(len(shoplifting_videos) * test_ratio))
train_shop = [v for v in shoplifting_videos if v not in test_shop]

test_normal = random.sample(normal_videos, int(len(normal_videos) * test_ratio))
train_normal = [v for v in normal_videos if v not in test_normal]

# 4. Extract frames
print("\nExtracting frames from videos...")
extract_frames_from_videos(train_shop, train_shop_dir, "shoplifting")
extract_frames_from_videos(train_normal, train_normal_dir, "normal")
extract_frames_from_videos(test_shop, test_shop_dir, "shoplifting")
extract_frames_from_videos(test_normal, test_normal_dir, "normal")

print("\nFrame extraction completed!")
print(f"Training Shoplifting frames: {len(os.listdir(train_shop_dir))}")
print(f"Training Normal frames: {len(os.listdir(train_normal_dir))}")
print(f"Testing Shoplifting frames: {len(os.listdir(test_shop_dir))}")
print(f"Testing Normal frames: {len(os.listdir(test_normal_dir))}")

Organizing dataset...
Dataset Statistics:
------------------
Abuse: 39 videos
Arrest: 26 videos
Arson: 22 videos
Assault: 23 videos
Burglary: 47 videos
Explosion: 23 videos
Fighting: 8 videos
Labels: 0 videos
RoadAccidents: 76 videos
Robbery: 105 videos
Shooting: 30 videos
Shoplifting: 28 videos
Stealing: 64 videos
Vandalism: 29 videos

Total Shoplifting videos: 92
Total Normal videos: 428

Extracting frames from videos...
Dataset Statistics:
------------------
Abuse: 39 videos
Arrest: 26 videos
Arson: 22 videos
Assault: 23 videos
Burglary: 47 videos
Explosion: 23 videos
Fighting: 8 videos
Labels: 0 videos
RoadAccidents: 76 videos
Robbery: 105 videos
Shooting: 30 videos
Shoplifting: 28 videos
Stealing: 64 videos
Vandalism: 29 videos

Total Shoplifting videos: 92
Total Normal videos: 428

Extracting frames from videos...

Processing shoplifting videos:   1%|▏         | 1/74 [00:00<00:08,  8.59it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting001_x264.mp4\Shoplifting001_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting005_x264.mp4\Shoplifting005_x264_0.mp4

Processing shoplifting videos:   4%|▍         | 3/74 [00:00<00:05, 12.55it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting006_x264.mp4\Shoplifting006_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting010_x264.mp4\Shoplifting010_x264_0.mp4

Processing shoplifting videos:   7%|▋         | 5/74 [00:00<00:05, 13.34it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting013_x264.mp4\Shoplifting013_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting015_x264.mp4\Shoplifting015_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting015_x264.mp4\Shoplifting015_x264_0.mp4

Processing shoplifting videos:   9%|▉         | 7/74 [00:00<00:06, 11.12it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting016_x264.mp4\Shoplifting016_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting018_x264.mp4\Shoplifting018_x264_0.mp4

Processing shoplifting videos:  15%|█▍        | 11/74 [00:01<00:06, 10.32it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting021_x264.mp4\Shoplifting021_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting024_x264.mp4\Shoplifting024_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting032_x264.mp4\Shoplifting032_x264_0.mp4

Processing shoplifting videos:  18%|█▊        | 13/74 [00:01<00:05, 10.74it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting036_x264.mp4\Shoplifting036_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting038_x264.mp4\Shoplifting038_x264_0.mp4

Processing shoplifting videos:  20%|██        | 15/74 [00:01<00:05, 10.25it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting039_x264.mp4\Shoplifting039_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting042_x264.mp4\Shoplifting042_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting045_x264.mp4\Shoplifting045_x264_0.mp4

Processing shoplifting videos:  26%|██▌       | 19/74 [00:01<00:04, 11.12it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting047_x264.mp4\Shoplifting047_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting048_x264.mp4\Shoplifting048_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting049_x264.mp4\Shoplifting049_x264_0.mp4

Processing shoplifting videos:  28%|██▊       | 21/74 [00:01<00:04, 11.40it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting050_x264.mp4\Shoplifting050_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting053_x264.mp4\Shoplifting053_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing006_x264.mp4\Stealing006_x264_0.mp4

Processing shoplifting videos:  34%|███▍      | 25/74 [00:02<00:04, 10.94it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing008_x264.mp4\Stealing008_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing009_x264.mp4\Stealing009_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing010_x264.mp4\Stealing010_x264_0.mp4

Processing shoplifting videos:  39%|███▉      | 29/74 [00:02<00:03, 13.09it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing012_x264.mp4\Stealing012_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing014_x264.mp4\Stealing014_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing015_x264.mp4\Stealing015_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing016_x264.mp4\Stealing016_x264_0.mp4

Processing shoplifting videos:  45%|████▍     | 33/74 [00:02<00:02, 14.33it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing017_x264.mp4\Stealing017_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing018_x264.mp4\Stealing018_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing021_x264.mp4\Stealing021_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing022_x264.mp4\Stealing022_x264_0.mp4

Processing shoplifting videos:  47%|████▋     | 35/74 [00:02<00:02, 14.05it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing023_x264.mp4\Stealing023_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing024_x264.mp4\Stealing024_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing026_x264.mp4\Stealing026_x264_0.mp4

Processing shoplifting videos:  50%|█████     | 37/74 [00:03<00:02, 13.66it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing027_x264.mp4\Stealing027_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing028_x264.mp4\Stealing028_x264_0.mp4

Processing shoplifting videos:  55%|█████▌    | 41/74 [00:03<00:02, 13.34it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing031_x264.mp4\Stealing031_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing036_x264.mp4\Stealing036_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing037_x264.mp4\Stealing037_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing042_x264.mp4\Stealing042_x264_0.mp4

Processing shoplifting videos:  61%|██████    | 45/74 [00:03<00:02, 14.16it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing044_x264.mp4\Stealing044_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing049_x264.mp4\Stealing049_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing050_x264.mp4\Stealing050_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing051_x264.mp4\Stealing051_x264_0.mp4

Processing shoplifting videos:  66%|██████▌   | 49/74 [00:03<00:01, 14.52it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing052_x264.mp4\Stealing052_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing054_x264.mp4\Stealing054_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing055_x264.mp4\Stealing055_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing060_x264.mp4\Stealing060_x264_0.mp4

Processing shoplifting videos:  69%|██████▉   | 51/74 [00:04<00:01, 14.84it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing061_x264.mp4\Stealing061_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing062_x264.mp4\Stealing062_x264_0.mp4

Processing shoplifting videos:  76%|███████▌  | 56/74 [00:04<00:01, 14.98it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing067_x264.mp4\Stealing067_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing070_x264.mp4\Stealing070_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing071_x264.mp4\Stealing071_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing073_x264.mp4\Stealing073_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing075_x264.mp4\Stealing075_x264_0.mp4

Processing shoplifting videos:  82%|████████▏ | 61/74 [00:04<00:00, 17.07it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing078_x264.mp4\Stealing078_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing080_x264.mp4\Stealing080_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing081_x264.mp4\Stealing081_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing082_x264.mp4\Stealing082_x264_0.mp4

Processing shoplifting videos:  88%|████████▊ | 65/74 [00:04<00:00, 16.97it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing087_x264.mp4\Stealing087_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing094_x264.mp4\Stealing094_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing097_x264.mp4\Stealing097_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing098_x264.mp4\Stealing098_x264_0.mp4

Processing shoplifting videos:  93%|█████████▎| 69/74 [00:05<00:00, 17.86it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing102_x264.mp4\Stealing102_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing104_x264.mp4\Stealing104_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing105_x264.mp4\Stealing105_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing106_x264.mp4\Stealing106_x264_0.mp4

Processing shoplifting videos:  99%|█████████▊| 73/74 [00:05<00:00, 16.48it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing108_x264.mp4\Stealing108_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing111_x264.mp4\Stealing111_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing112_x264.mp4\Stealing112_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing113_x264.mp4\Stealing113_x264_0.mp4

Processing shoplifting videos: 100%|██████████| 74/74 [00:05<00:00, 13.55it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing114_x264.mp4\Stealing114_x264_0.mp4

Processing normal videos:   1%|          | 3/343 [00:00<00:22, 15.18it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse001_x264.mp4\Abuse001_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse003_x264.mp4\Abuse003_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse004_x264.mp4\Abuse004_x264_0.mp4

Processing normal videos:   1%|▏         | 5/343 [00:00<00:21, 15.41it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse007_x264.mp4\Abuse007_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse008_x264.mp4\Abuse008_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse010_x264.mp4\Abuse010_x264_0.mp4

Processing normal videos:   3%|▎         | 9/343 [00:00<00:24, 13.88it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse012_x264.mp4\Abuse012_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse013_x264.mp4\Abuse013_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse014_x264.mp4\Abuse014_x264_0.mp4

Processing normal videos:   4%|▍         | 13/343 [00:00<00:22, 14.37it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse016_x264.mp4\Abuse016_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse017_x264.mp4\Abuse017_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse018_x264.mp4\Abuse018_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse020_x264.mp4\Abuse020_x264_0.mp4

Processing normal videos:   5%|▍         | 17/343 [00:01<00:21, 15.43it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse021_x264.mp4\Abuse021_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse022_x264.mp4\Abuse022_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse023_x264.mp4\Abuse023_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse024_x264.mp4\Abuse024_x264_0.mp4

Processing normal videos:   6%|▌         | 21/343 [00:01<00:21, 15.12it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse025_x264.mp4\Abuse025_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse026_x264.mp4\Abuse026_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse027_x264.mp4\Abuse027_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse031_x264.mp4\Abuse031_x264_0.mp4

Processing normal videos:   7%|▋         | 23/343 [00:01<00:19, 16.08it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse033_x264.mp4\Abuse033_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse034_x264.mp4\Abuse034_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse035_x264.mp4\Abuse035_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse037_x264.mp4\Abuse037_x264_0.mp4

Processing normal videos:   8%|▊         | 28/343 [00:01<00:24, 12.93it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse039_x264.mp4\Abuse039_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse041_x264.mp4\Abuse041_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse042_x264.mp4\Abuse042_x264_0.mp4

Processing normal videos:   9%|▊         | 30/343 [00:02<00:28, 10.79it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse043_x264.mp4\Abuse043_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse044_x264.mp4\Abuse044_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse048_x264.mp4\Abuse048_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse050_x264.mp4\Abuse050_x264_0.mp4

Processing normal videos:  10%|█         | 36/343 [00:02<00:22, 13.35it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest001_x264.mp4\Arrest001_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest003_x264.mp4\Arrest003_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest004_x264.mp4\Arrest004_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest005_x264.mp4\Arrest005_x264_0.mp4

Processing normal videos:  12%|█▏        | 40/343 [00:02<00:19, 15.59it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest006_x264.mp4\Arrest006_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest009_x264.mp4\Arrest009_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest011_x264.mp4\Arrest011_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest014_x264.mp4\Arrest014_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest019_x264.mp4\Arrest019_x264_0.mp4

Processing normal videos:  13%|█▎        | 45/343 [00:03<00:16, 18.05it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest024_x264.mp4\Arrest024_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest025_x264.mp4\Arrest025_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest028_x264.mp4\Arrest028_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest031_x264.mp4\Arrest031_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest032_x264.mp4\Arrest032_x264_0.mp4

Processing normal videos:  14%|█▍        | 49/343 [00:03<00:16, 17.77it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest036_x264.mp4\Arrest036_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest037_x264.mp4\Arrest037_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest038_x264.mp4\Arrest038_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest040_x264.mp4\Arrest040_x264_0.mp4

Processing normal videos:  15%|█▌        | 53/343 [00:03<00:17, 16.50it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest041_x264.mp4\Arrest041_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest048_x264.mp4\Arrest048_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson002_x264.mp4\Arson002_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson003_x264.mp4\Arson003_x264_0.mp4

Processing normal videos:  17%|█▋        | 57/343 [00:03<00:20, 13.99it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson005_x264.mp4\Arson005_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson008_x264.mp4\Arson008_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson011_x264.mp4\Arson011_x264_0.mp4

Processing normal videos:  18%|█▊        | 62/343 [00:04<00:16, 16.80it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson014_x264.mp4\Arson014_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson016_x264.mp4\Arson016_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson020_x264.mp4\Arson020_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson023_x264.mp4\Arson023_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson024_x264.mp4\Arson024_x264_0.mp4

Processing normal videos:  20%|█▉        | 67/343 [00:04<00:15, 17.96it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson027_x264.mp4\Arson027_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson028_x264.mp4\Arson028_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson029_x264.mp4\Arson029_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson034_x264.mp4\Arson034_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson039_x264.mp4\Arson039_x264_0.mp4

Processing normal videos:  21%|██        | 71/343 [00:04<00:14, 18.13it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson041_x264.mp4\Arson041_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson045_x264.mp4\Arson045_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson047_x264.mp4\Arson047_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson050_x264.mp4\Arson050_x264_0.mp4

Processing normal videos:  22%|██▏       | 75/343 [00:04<00:15, 17.33it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault004_x264.mp4\Assault004_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault005_x264.mp4\Assault005_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault007_x264.mp4\Assault007_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault009_x264.mp4\Assault009_x264_0.mp4

Processing normal videos:  23%|██▎       | 79/343 [00:05<00:16, 16.28it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault011_x264.mp4\Assault011_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault013_x264.mp4\Assault013_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault014_x264.mp4\Assault014_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault015_x264.mp4\Assault015_x264_0.mp4

Processing normal videos:  24%|██▍       | 83/343 [00:05<00:15, 16.86it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault017_x264.mp4\Assault017_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault019_x264.mp4\Assault019_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault025_x264.mp4\Assault025_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault028_x264.mp4\Assault028_x264_0.mp4

Processing normal videos:  25%|██▌       | 87/343 [00:05<00:14, 17.32it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault033_x264.mp4\Assault033_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault034_x264.mp4\Assault034_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault037_x264.mp4\Assault037_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault040_x264.mp4\Assault040_x264_0.mp4

Processing normal videos:  27%|██▋       | 91/343 [00:05<00:14, 17.57it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault045_x264.mp4\Assault045_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault048_x264.mp4\Assault048_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault049_x264.mp4\Assault049_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary004_x264.mp4\Burglary004_x264_0.mp4

Processing normal videos:  28%|██▊       | 95/343 [00:06<00:15, 16.08it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary009_x264.mp4\Burglary009_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary011_x264.mp4\Burglary011_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary012_x264.mp4\Burglary012_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary015_x264.mp4\Burglary015_x264_0.mp4

Processing normal videos:  29%|██▉       | 99/343 [00:06<00:14, 17.19it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary018_x264.mp4\Burglary018_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary019_x264.mp4\Burglary019_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary020_x264.mp4\Burglary020_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary021_x264.mp4\Burglary021_x264_0.mp4

Processing normal videos:  30%|███       | 103/343 [00:06<00:14, 16.59it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary022_x264.mp4\Burglary022_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary024_x264.mp4\Burglary024_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary026_x264.mp4\Burglary026_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary027_x264.mp4\Burglary027_x264_0.mp4

Processing normal videos:  31%|███       | 105/343 [00:06<00:14, 16.93it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary034_x264.mp4\Burglary034_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary035_x264.mp4\Burglary035_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary036_x264.mp4\Burglary036_x264_0.mp4

Processing normal videos:  32%|███▏      | 109/343 [00:06<00:15, 15.33it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary037_x264.mp4\Burglary037_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary041_x264.mp4\Burglary041_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary046_x264.mp4\Burglary046_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary053_x264.mp4\Burglary053_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary056_x264.mp4\Burglary056_x264_0.mp4

Processing normal videos:  33%|███▎      | 114/343 [00:07<00:13, 17.05it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary066_x264.mp4\Burglary066_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary069_x264.mp4\Burglary069_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary072_x264.mp4\Burglary072_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary074_x264.mp4\Burglary074_x264_0.mp4

Processing normal videos:  34%|███▍      | 118/343 [00:07<00:13, 17.06it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary077_x264.mp4\Burglary077_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary080_x264.mp4\Burglary080_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary082_x264.mp4\Burglary082_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary085_x264.mp4\Burglary085_x264_0.mp4

Processing normal videos:  35%|███▍      | 120/343 [00:07<00:12, 17.52it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary087_x264.mp4\Burglary087_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary089_x264.mp4\Burglary089_x264_0.mp4

Processing normal videos:  36%|███▌      | 124/343 [00:07<00:14, 14.87it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary090_x264.mp4\Burglary090_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary091_x264.mp4\Burglary091_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary094_x264.mp4\Burglary094_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary099_x264.mp4\Burglary099_x264_0.mp4

Processing normal videos:  37%|███▋      | 128/343 [00:08<00:13, 16.08it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion004_x264.mp4\Explosion004_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion006_x264.mp4\Explosion006_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion008_x264.mp4\Explosion008_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion009_x264.mp4\Explosion009_x264_0.mp4

Processing normal videos:  38%|███▊      | 132/343 [00:08<00:12, 17.41it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion011_x264.mp4\Explosion011_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion013_x264.mp4\Explosion013_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion014_x264.mp4\Explosion014_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion017_x264.mp4\Explosion017_x264_0.mp4

Processing normal videos:  40%|███▉      | 136/343 [00:08<00:11, 17.58it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion020_x264.mp4\Explosion020_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion023_x264.mp4\Explosion023_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion024_x264.mp4\Explosion024_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion026_x264.mp4\Explosion026_x264_0.mp4

Processing normal videos:  41%|████      | 140/343 [00:08<00:11, 17.34it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion028_x264.mp4\Explosion028_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion029_x264.mp4\Explosion029_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion033_x264.mp4\Explosion033_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion037_x264.mp4\Explosion037_x264_0.mp4

Processing normal videos:  42%|████▏     | 144/343 [00:08<00:11, 17.61it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion042_x264.mp4\Explosion042_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion047_x264.mp4\Explosion047_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion052_x264.mp4\Explosion052_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Fighting\Fighting002_x264.mp4\Fighting002_x264_0.mp4

Processing normal videos:  43%|████▎     | 148/343 [00:09<00:11, 16.97it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Fighting\Fighting005_x264.mp4\Fighting005_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Fighting\Fighting009_x264.mp4\Fighting009_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Fighting\Fighting014_x264.mp4\Fighting014_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents001_x264.mp4\RoadAccidents001_x264_0.mp4

Processing normal videos:  44%|████▍     | 151/343 [00:09<00:11, 16.26it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents006_x264.mp4\RoadAccidents006_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents007_x264.mp4\RoadAccidents007_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents008_x264.mp4\RoadAccidents008_x264_0.mp4

Processing normal videos:  45%|████▌     | 156/343 [00:09<00:10, 17.62it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents015_x264.mp4\RoadAccidents015_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents016_x264.mp4\RoadAccidents016_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents018_x264.mp4\RoadAccidents018_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents019_x264.mp4\RoadAccidents019_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents020_x264.mp4\RoadAccidents020_x264_0.mp4

Processing normal videos:  47%|████▋     | 160/343 [00:09<00:10, 17.14it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents023_x264.mp4\RoadAccidents023_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents024_x264.mp4\RoadAccidents024_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents025_x264.mp4\RoadAccidents025_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents031_x264.mp4\RoadAccidents031_x264_0.mp4

Processing normal videos:  48%|████▊     | 164/343 [00:10<00:11, 15.55it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents032_x264.mp4\RoadAccidents032_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents034_x264.mp4\RoadAccidents034_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents036_x264.mp4\RoadAccidents036_x264_0.mp4

Processing normal videos:  49%|████▉     | 168/343 [00:10<00:10, 16.80it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents037_x264.mp4\RoadAccidents037_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents048_x264.mp4\RoadAccidents048_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents050_x264.mp4\RoadAccidents050_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents057_x264.mp4\RoadAccidents057_x264_0.mp4

Processing normal videos:  50%|█████     | 173/343 [00:10<00:09, 18.46it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents059_x264.mp4\RoadAccidents059_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents064_x264.mp4\RoadAccidents064_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents066_x264.mp4\RoadAccidents066_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents074_x264.mp4\RoadAccidents074_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents077_x264.mp4\RoadAccidents077_x264_0.mp4

Processing normal videos:  51%|█████▏    | 176/343 [00:10<00:08, 19.21it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents079_x264.mp4\RoadAccidents079_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents080_x264.mp4\RoadAccidents080_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents082_x264.mp4\RoadAccidents082_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents083_x264.mp4\RoadAccidents083_x264_0.mp4

Processing normal videos:  53%|█████▎    | 181/343 [00:11<00:08, 18.72it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents088_x264.mp4\RoadAccidents088_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents089_x264.mp4\RoadAccidents089_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents090_x264.mp4\RoadAccidents090_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents091_x264.mp4\RoadAccidents091_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents092_x264.mp4\RoadAccidents092_x264_0.mp4

Processing normal videos:  55%|█████▍    | 187/343 [00:11<00:08, 19.29it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents093_x264.mp4\RoadAccidents093_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents094_x264.mp4\RoadAccidents094_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents098_x264.mp4\RoadAccidents098_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents099_x264.mp4\RoadAccidents099_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents105_x264.mp4\RoadAccidents105_x264_0.mp4

Processing normal videos:  56%|█████▌    | 192/343 [00:11<00:07, 19.57it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents106_x264.mp4\RoadAccidents106_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents111_x264.mp4\RoadAccidents111_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents113_x264.mp4\RoadAccidents113_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents114_x264.mp4\RoadAccidents114_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents115_x264.mp4\RoadAccidents115_x264_0.mp4

Processing normal videos:  57%|█████▋    | 196/343 [00:11<00:07, 18.80it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents117_x264.mp4\RoadAccidents117_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents118_x264.mp4\RoadAccidents118_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents119_x264.mp4\RoadAccidents119_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents120_x264.mp4\RoadAccidents120_x264_0.mp4

Processing normal videos:  58%|█████▊    | 200/343 [00:12<00:07, 18.67it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents121_x264.mp4\RoadAccidents121_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents123_x264.mp4\RoadAccidents123_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents124_x264.mp4\RoadAccidents124_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents125_x264.mp4\RoadAccidents125_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents126_x264.mp4\RoadAccidents126_x264_0.mp4

Processing normal videos:  59%|█████▉    | 204/343 [00:12<00:08, 17.07it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents127_x264.mp4\RoadAccidents127_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents130_x264.mp4\RoadAccidents130_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents131_x264.mp4\RoadAccidents131_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents132_x264.mp4\RoadAccidents132_x264_0.mp4

Processing normal videos:  61%|██████    | 209/343 [00:12<00:07, 18.36it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents135_x264.mp4\RoadAccidents135_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents137_x264.mp4\RoadAccidents137_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents138_x264.mp4\RoadAccidents138_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents139_x264.mp4\RoadAccidents139_x264_0.mp4

Processing normal videos:  62%|██████▏   | 211/343 [00:12<00:07, 16.93it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents140_x264.mp4\RoadAccidents140_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents141_x264.mp4\RoadAccidents141_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents145_x264.mp4\RoadAccidents145_x264_0.mp4

Processing normal videos:  63%|██████▎   | 215/343 [00:13<00:07, 16.04it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents146_x264.mp4\RoadAccidents146_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents149_x264.mp4\RoadAccidents149_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents150_x264.mp4\RoadAccidents150_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery001_x264.mp4\Robbery001_x264_0.mp4

Processing normal videos:  64%|██████▍   | 219/343 [00:13<00:07, 16.08it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery002_x264.mp4\Robbery002_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery003_x264.mp4\Robbery003_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery004_x264.mp4\Robbery004_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery006_x264.mp4\Robbery006_x264_0.mp4

Processing normal videos:  65%|██████▌   | 223/343 [00:13<00:08, 14.18it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery007_x264.mp4\Robbery007_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery008_x264.mp4\Robbery008_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery009_x264.mp4\Robbery009_x264_0.mp4

Processing normal videos:  66%|██████▌   | 227/343 [00:13<00:08, 13.98it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery010_x264.mp4\Robbery010_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery016_x264.mp4\Robbery016_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery017_x264.mp4\Robbery017_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery018_x264.mp4\Robbery018_x264_0.mp4

Processing normal videos:  67%|██████▋   | 231/343 [00:14<00:07, 14.36it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery019_x264.mp4\Robbery019_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery022_x264.mp4\Robbery022_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery023_x264.mp4\Robbery023_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery025_x264.mp4\Robbery025_x264_0.mp4

Processing normal videos:  69%|██████▊   | 235/343 [00:14<00:07, 15.31it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery028_x264.mp4\Robbery028_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery030_x264.mp4\Robbery030_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery035_x264.mp4\Robbery035_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery036_x264.mp4\Robbery036_x264_0.mp4

Processing normal videos:  69%|██████▉   | 238/343 [00:14<00:06, 17.08it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery038_x264.mp4\Robbery038_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery040_x264.mp4\Robbery040_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery041_x264.mp4\Robbery041_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery042_x264.mp4\Robbery042_x264_0.mp4

Processing normal videos:  71%|███████   | 243/343 [00:14<00:05, 16.89it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery043_x264.mp4\Robbery043_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery047_x264.mp4\Robbery047_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery048_x264.mp4\Robbery048_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery049_x264.mp4\Robbery049_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery050_x264.mp4\Robbery050_x264_0.mp4

Processing normal videos:  72%|███████▏  | 247/343 [00:15<00:05, 17.98it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery051_x264.mp4\Robbery051_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery053_x264.mp4\Robbery053_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery054_x264.mp4\Robbery054_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery056_x264.mp4\Robbery056_x264_0.mp4

Processing normal videos:  73%|███████▎  | 251/343 [00:15<00:05, 16.86it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery057_x264.mp4\Robbery057_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery058_x264.mp4\Robbery058_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery060_x264.mp4\Robbery060_x264_0.mp4

Processing normal videos:  74%|███████▍  | 255/343 [00:15<00:05, 16.16it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery061_x264.mp4\Robbery061_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery063_x264.mp4\Robbery063_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery065_x264.mp4\Robbery065_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery066_x264.mp4\Robbery066_x264_0.mp4

Processing normal videos:  76%|███████▌  | 259/343 [00:15<00:05, 15.44it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery067_x264.mp4\Robbery067_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery071_x264.mp4\Robbery071_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery077_x264.mp4\Robbery077_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery078_x264.mp4\Robbery078_x264_0.mp4

Processing normal videos:  77%|███████▋  | 264/343 [00:16<00:04, 17.66it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery080_x264.mp4\Robbery080_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery081_x264.mp4\Robbery081_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery083_x264.mp4\Robbery083_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery085_x264.mp4\Robbery085_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery087_x264.mp4\Robbery087_x264_0.mp4

Processing normal videos:  78%|███████▊  | 268/343 [00:16<00:04, 17.94it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery091_x264.mp4\Robbery091_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery094_x264.mp4\Robbery094_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery095_x264.mp4\Robbery095_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery096_x264.mp4\Robbery096_x264_0.mp4

Processing normal videos:  79%|███████▉  | 272/343 [00:16<00:04, 17.67it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery100_x264.mp4\Robbery100_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery102_x264.mp4\Robbery102_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery103_x264.mp4\Robbery103_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery104_x264.mp4\Robbery104_x264_0.mp4

Processing normal videos:  80%|████████  | 276/343 [00:16<00:03, 17.69it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery105_x264.mp4\Robbery105_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery107_x264.mp4\Robbery107_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery109_x264.mp4\Robbery109_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery110_x264.mp4\Robbery110_x264_0.mp4

Processing normal videos:  81%|████████  | 278/343 [00:16<00:04, 16.15it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery111_x264.mp4\Robbery111_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery114_x264.mp4\Robbery114_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery115_x264.mp4\Robbery115_x264_0.mp4

Processing normal videos:  82%|████████▏ | 282/343 [00:17<00:03, 16.83it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery117_x264.mp4\Robbery117_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery118_x264.mp4\Robbery118_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery119_x264.mp4\Robbery119_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery122_x264.mp4\Robbery122_x264_0.mp4

Processing normal videos:  83%|████████▎ | 286/343 [00:17<00:03, 17.03it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery126_x264.mp4\Robbery126_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery127_x264.mp4\Robbery127_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery129_x264.mp4\Robbery129_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery130_x264.mp4\Robbery130_x264_0.mp4

Processing normal videos:  85%|████████▍ | 290/343 [00:17<00:02, 17.73it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery133_x264.mp4\Robbery133_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery139_x264.mp4\Robbery139_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery140_x264.mp4\Robbery140_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery142_x264.mp4\Robbery142_x264_0.mp4

Processing normal videos:  86%|████████▌ | 294/343 [00:17<00:02, 16.62it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery145_x264.mp4\Robbery145_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery146_x264.mp4\Robbery146_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery149_x264.mp4\Robbery149_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery150_x264.mp4\Robbery150_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting002_x264.mp4\Shooting002_x264_0.mp4

Processing normal videos:  87%|████████▋ | 300/343 [00:18<00:02, 17.76it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting005_x264.mp4\Shooting005_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting007_x264.mp4\Shooting007_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting008_x264.mp4\Shooting008_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting010_x264.mp4\Shooting010_x264_0.mp4

Processing normal videos:  89%|████████▊ | 304/343 [00:18<00:02, 17.50it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting011_x264.mp4\Shooting011_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting013_x264.mp4\Shooting013_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting015_x264.mp4\Shooting015_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting018_x264.mp4\Shooting018_x264_0.mp4

Processing normal videos:  90%|████████▉ | 308/343 [00:18<00:02, 17.08it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting019_x264.mp4\Shooting019_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting020_x264.mp4\Shooting020_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting021_x264.mp4\Shooting021_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting022_x264.mp4\Shooting022_x264_0.mp4

Processing normal videos:  91%|█████████ | 311/343 [00:18<00:01, 18.21it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting025_x264.mp4\Shooting025_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting026_x264.mp4\Shooting026_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting028_x264.mp4\Shooting028_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting029_x264.mp4\Shooting029_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting030_x264.mp4\Shooting030_x264_0.mp4

Processing normal videos:  92%|█████████▏| 316/343 [00:19<00:01, 17.40it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting033_x264.mp4\Shooting033_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting036_x264.mp4\Shooting036_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting038_x264.mp4\Shooting038_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting042_x264.mp4\Shooting042_x264_0.mp4

Processing normal videos:  93%|█████████▎| 320/343 [00:19<00:01, 18.13it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting048_x264.mp4\Shooting048_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting052_x264.mp4\Shooting052_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism001_x264.mp4\Vandalism001_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism002_x264.mp4\Vandalism002_x264_0.mp4

Processing normal videos:  95%|█████████▍| 325/343 [00:19<00:00, 18.86it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism003_x264.mp4\Vandalism003_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism004_x264.mp4\Vandalism004_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism005_x264.mp4\Vandalism005_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism007_x264.mp4\Vandalism007_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism013_x264.mp4\Vandalism013_x264_0.mp4

Processing normal videos:  96%|█████████▌| 330/343 [00:19<00:00, 18.77it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism015_x264.mp4\Vandalism015_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism017_x264.mp4\Vandalism017_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism019_x264.mp4\Vandalism019_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism021_x264.mp4\Vandalism021_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism024_x264.mp4\Vandalism024_x264_0.mp4

Processing normal videos:  97%|█████████▋| 334/343 [00:20<00:00, 17.99it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism025_x264.mp4\Vandalism025_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism033_x264.mp4\Vandalism033_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism034_x264.mp4\Vandalism034_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism035_x264.mp4\Vandalism035_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism036_x264.mp4\Vandalism036_x264_0.mp4

Processing normal videos:  99%|█████████▉| 340/343 [00:20<00:00, 17.76it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism037_x264.mp4\Vandalism037_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism038_x264.mp4\Vandalism038_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism040_x264.mp4\Vandalism040_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism042_x264.mp4\Vandalism042_x264_0.mp4

Processing normal videos: 100%|██████████| 343/343 [00:20<00:00, 16.66it/s]
Processing normal videos: 100%|██████████| 343/343 [00:20<00:00, 16.66it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism043_x264.mp4\Vandalism043_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism045_x264.mp4\Vandalism045_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism046_x264.mp4\Vandalism046_x264_0.mp4

Processing shoplifting videos:   0%|          | 0/18 [00:00<?, ?it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing101_x264.mp4\Stealing101_x264_0.mp4

Processing shoplifting videos:  22%|██▏       | 4/18 [00:00<00:00, 16.05it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting026_x264.mp4\Shoplifting026_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting007_x264.mp4\Shoplifting007_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing011_x264.mp4\Stealing011_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing007_x264.mp4\Stealing007_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing007_x264.mp4\Stealing007_x264_0.mp4

Processing shoplifting videos:  44%|████▍     | 8/18 [00:00<00:00, 15.69it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing002_x264.mp4\Stealing002_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting037_x264.mp4\Shoplifting037_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting025_x264.mp4\Shoplifting025_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing107_x264.mp4\Stealing107_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing107_x264.mp4\Stealing107_x264_0.mp4

Processing shoplifting videos:  67%|██████▋   | 12/18 [00:00<00:00, 16.08it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing074_x264.mp4\Stealing074_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting022_x264.mp4\Shoplifting022_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing083_x264.mp4\Stealing083_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing047_x264.mp4\Stealing047_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing047_x264.mp4\Stealing047_x264_0.mp4

Processing shoplifting videos:  78%|███████▊  | 14/18 [00:00<00:00, 14.51it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting009_x264.mp4\Shoplifting009_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shoplifting\Shoplifting054_x264.mp4\Shoplifting054_x264_0.mp4

Processing shoplifting videos:  89%|████████▉ | 16/18 [00:01<00:00, 15.58it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing003_x264.mp4\Stealing003_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing066_x264.mp4\Stealing066_x264_0.mp4

Processing shoplifting videos: 100%|██████████| 18/18 [00:01<00:00, 15.91it/s]
Processing shoplifting videos: 100%|██████████| 18/18 [00:01<00:00, 15.91it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Stealing\Stealing093_x264.mp4\Stealing093_x264_0.mp4

Processing normal videos:   0%|          | 0/85 [00:00<?, ?it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse019_x264.mp4\Abuse019_x264_0.mp4

Processing normal videos:   2%|▏         | 2/85 [00:00<00:05, 16.33it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery031_x264.mp4\Robbery031_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault030_x264.mp4\Assault030_x264_0.mp4

Processing normal videos:   5%|▍         | 4/85 [00:00<00:05, 16.15it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery148_x264.mp4\Robbery148_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery099_x264.mp4\Robbery099_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery099_x264.mp4\Robbery099_x264_0.mp4

Processing normal videos:   7%|▋         | 6/85 [00:00<00:04, 16.50it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery136_x264.mp4\Robbery136_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery020_x264.mp4\Robbery020_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents067_x264.mp4\RoadAccidents067_x264_0.mp4Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents067_x264.mp4\RoadAccidents067_x264_0.mp4

Processing normal videos:   9%|▉         | 8/85 [00:00<00:05, 15.32it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary007_x264.mp4\Burglary007_x264_0.mp4

Processing normal videos:  12%|█▏        | 10/85 [00:00<00:04, 16.19it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents095_x264.mp4\RoadAccidents095_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery052_x264.mp4\Robbery052_x264_0.mp4

Processing normal videos:  14%|█▍        | 12/85 [00:00<00:04, 16.57it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary071_x264.mp4\Burglary071_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism030_x264.mp4\Vandalism030_x264_0.mp4

Processing normal videos:  16%|█▋        | 14/85 [00:00<00:04, 17.27it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse006_x264.mp4\Abuse006_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting031_x264.mp4\Shooting031_x264_0.mp4

Processing normal videos:  19%|█▉        | 16/85 [00:00<00:03, 17.39it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism026_x264.mp4\Vandalism026_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson040_x264.mp4\Arson040_x264_0.mp4

Processing normal videos:  21%|██        | 18/85 [00:01<00:03, 17.47it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery131_x264.mp4\Robbery131_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents076_x264.mp4\RoadAccidents076_x264_0.mp4

Processing normal videos:  24%|██▎       | 20/85 [00:01<00:04, 15.33it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion035_x264.mp4\Explosion035_x264_0.mp4

Processing normal videos:  26%|██▌       | 22/85 [00:01<00:03, 16.09it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson036_x264.mp4\Arson036_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary001_x264.mp4\Burglary001_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting034_x264.mp4\Shooting034_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion032_x264.mp4\Explosion032_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest023_x264.mp4\Arrest023_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion032_x264.mp4\Explosion032_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest023_x264.mp4\Arrest023_x264_0.mp4

Processing normal videos:  33%|███▎      | 28/85 [00:01<00:03, 18.20it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest013_x264.mp4\Arrest013_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents013_x264.mp4\RoadAccidents013_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest017_x264.mp4\Arrest017_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Fighting\Fighting007_x264.mp4\Fighting007_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Fighting\Fighting007_x264.mp4\Fighting007_x264_0.mp4

Processing normal videos:  38%|███▊      | 32/85 [00:01<00:02, 17.89it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion038_x264.mp4\Explosion038_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery062_x264.mp4\Robbery062_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary048_x264.mp4\Burglary048_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism028_x264.mp4\Vandalism028_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism028_x264.mp4\Vandalism028_x264_0.mp4

Processing normal videos:  42%|████▏     | 36/85 [00:02<00:03, 15.91it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse028_x264.mp4\Abuse028_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting009_x264.mp4\Shooting009_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents107_x264.mp4\RoadAccidents107_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery015_x264.mp4\Robbery015_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery015_x264.mp4\Robbery015_x264_0.mp4

Processing normal videos:  45%|████▍     | 38/85 [00:02<00:02, 15.90it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest042_x264.mp4\Arrest042_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents011_x264.mp4\RoadAccidents011_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest002_x264.mp4\Arrest002_x264_0.mp4

Processing normal videos:  48%|████▊     | 41/85 [00:02<00:02, 17.31it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery024_x264.mp4\Robbery024_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary086_x264.mp4\Burglary086_x264_0.mp4

Processing normal videos:  51%|█████     | 43/85 [00:02<00:02, 17.44it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism044_x264.mp4\Vandalism044_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery082_x264.mp4\Robbery082_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery072_x264.mp4\Robbery072_x264_0.mp4

Processing normal videos:  54%|█████▍    | 46/85 [00:02<00:02, 17.89it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Fighting\Fighting012_x264.mp4\Fighting012_x264_0.mp4

Processing normal videos:  56%|█████▋    | 48/85 [00:02<00:02, 17.48it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery045_x264.mp4\Robbery045_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault022_x264.mp4\Assault022_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery137_x264.mp4\Robbery137_x264_0.mp4

Processing normal videos:  59%|█████▉    | 50/85 [00:02<00:02, 17.44it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse045_x264.mp4\Abuse045_x264_0.mp4

Processing normal videos:  62%|██████▏   | 53/85 [00:03<00:01, 18.65it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse030_x264.mp4\Abuse030_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery106_x264.mp4\Robbery106_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary013_x264.mp4\Burglary013_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting043_x264.mp4\Shooting043_x264_0.mp4

Processing normal videos:  65%|██████▍   | 55/85 [00:03<00:01, 18.90it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary084_x264.mp4\Burglary084_x264_0.mp4

Processing normal videos:  68%|██████▊   | 58/85 [00:03<00:01, 19.81it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary017_x264.mp4\Burglary017_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arrest\Arrest022_x264.mp4\Arrest022_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents103_x264.mp4\RoadAccidents103_x264_0.mp4

Processing normal videos:  71%|███████   | 60/85 [00:03<00:01, 19.20it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery088_x264.mp4\Robbery088_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Vandalism\Vandalism047_x264.mp4\Vandalism047_x264_0.mp4

Processing normal videos:  73%|███████▎  | 62/85 [00:03<00:01, 19.16it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Fighting\Fighting013_x264.mp4\Fighting013_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Arson\Arson042_x264.mp4\Arson042_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents003_x264.mp4\RoadAccidents003_x264_0.mp4

Processing normal videos:  75%|███████▌  | 64/85 [00:03<00:01, 18.50it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Fighting\Fighting003_x264.mp4\Fighting003_x264_0.mp4

Processing normal videos:  78%|███████▊  | 66/85 [00:03<00:01, 17.47it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault047_x264.mp4\Assault047_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery112_x264.mp4\Robbery112_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary051_x264.mp4\Burglary051_x264_0.mp4

Processing normal videos:  80%|████████  | 68/85 [00:03<00:00, 18.05it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery120_x264.mp4\Robbery120_x264_0.mp4

Processing normal videos:  82%|████████▏ | 70/85 [00:04<00:00, 17.34it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery097_x264.mp4\Robbery097_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse047_x264.mp4\Abuse047_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery064_x264.mp4\Robbery064_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault002_x264.mp4\Assault002_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery013_x264.mp4\Robbery013_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Assault\Assault002_x264.mp4\Assault002_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery013_x264.mp4\Robbery013_x264_0.mp4

Processing normal videos:  86%|████████▌ | 73/85 [00:04<00:00, 17.81it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary023_x264.mp4\Burglary023_x264_0.mp4

Processing normal videos:  91%|█████████ | 77/85 [00:04<00:00, 15.64it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\RoadAccidents\RoadAccidents109_x264.mp4\RoadAccidents109_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary055_x264.mp4\Burglary055_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery093_x264.mp4\Robbery093_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery123_x264.mp4\Robbery123_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery123_x264.mp4\Robbery123_x264_0.mp4

Processing normal videos:  95%|█████████▌| 81/85 [00:04<00:00, 17.12it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery029_x264.mp4\Robbery029_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Robbery\Robbery121_x264.mp4\Robbery121_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Explosion\Explosion022_x264.mp4\Explosion022_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting041_x264.mp4\Shooting041_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting050_x264.mp4\Shooting050_x264_0.mp4Successfully extracted 30 frames from extracted_folder/DCSASS\Shooting\Shooting050_x264.mp4\Shooting050_x264_0.mp4

Processing normal videos: 100%|██████████| 85/85 [00:04<00:00, 17.11it/s]

Successfully extracted 30 frames from extracted_folder/DCSASS\Abuse\Abuse036_x264.mp4\Abuse036_x264_0.mp4
Successfully extracted 30 frames from extracted_folder/DCSASS\Burglary\Burglary014_x264.mp4\Burglary014_x264_0.mp4

Frame extraction completed!
Training Shoplifting frames: 2220
Training Normal frames: 10290
Testing Shoplifting frames: 540
Testing Normal frames: 2550

In [17]:
# Load the dataset from extracted frames
output_base = "processed_frames"

# Function to count frames in a directory
def count_frames_in_dir(directory):
    if not os.path.exists(directory):
        return 0
    return len([f for f in os.listdir(directory) if f.endswith(('.jpg', '.jpeg', '.png'))])

# Count frames in each directory
train_shop_frames = count_frames_in_dir(os.path.join(output_base, "train", "shoplifting"))
train_normal_frames = count_frames_in_dir(os.path.join(output_base, "train", "normal"))
test_shop_frames = count_frames_in_dir(os.path.join(output_base, "test", "shoplifting"))
test_normal_frames = count_frames_in_dir(os.path.join(output_base, "test", "normal"))

print("Dataset Statistics:")
print("-----------------")
print(f"Training set:")
print(f"  - Shoplifting frames: {train_shop_frames}")
print(f"  - Normal frames: {train_normal_frames}")
print(f"\nTesting set:")
print(f"  - Shoplifting frames: {test_shop_frames}")
print(f"  - Normal frames: {test_normal_frames}")
print(f"\nTotal frames: {train_shop_frames + train_normal_frames + test_shop_frames + test_normal_frames}")

Dataset Statistics:
-----------------
Training set:
  - Shoplifting frames: 2220
  - Normal frames: 10290

Testing set:
  - Shoplifting frames: 540
  - Normal frames: 2550

Total frames: 15600

In [30]:
import pandas as pd
# Create a DataFrame with frame information
frame_data = []

# Process training set
train_shop_dir = os.path.join(output_base, "train", "shoplifting")
train_normal_dir = os.path.join(output_base, "train", "normal")

if os.path.exists(train_shop_dir):
    for frame in os.listdir(train_shop_dir):
        if frame.endswith(('.jpg', '.jpeg', '.png')):
            frame_data.append({
                'frame_path': os.path.join(train_shop_dir, frame),
                'label': 'shoplifting',
                'split': 'train'
            })

if os.path.exists(train_normal_dir):
    for frame in os.listdir(train_normal_dir):
        if frame.endswith(('.jpg', '.jpeg', '.png')):
            frame_data.append({
                'frame_path': os.path.join(train_normal_dir, frame),
                'label': 'normal',
                'split': 'train'
            })

# Create DataFrame
df = pd.DataFrame(frame_data)

print("DataFrame Summary:")
print("-----------------")
print(f"Total frames: {len(df)}")
print("\nLabel distribution:")
print(df['label'].value_counts())
print("\nSplit distribution:")
print(df['split'].value_counts())
print("\nFirst few rows:")
print(df.head())

DataFrame Summary:
-----------------
Total frames: 12510

Label distribution:
label
normal         10290
shoplifting     2220
Name: count, dtype: int64

Split distribution:
split
train    12510
Name: count, dtype: int64

First few rows:
                                          frame_path        label  split
0  processed_frames\train\shoplifting\shoplifting...  shoplifting  train
1  processed_frames\train\shoplifting\shoplifting...  shoplifting  train
2  processed_frames\train\shoplifting\shoplifting...  shoplifting  train
3  processed_frames\train\shoplifting\shoplifting...  shoplifting  train
4  processed_frames\train\shoplifting\shoplifting...  shoplifting  train

In [26]:
def extract_features(frame_dir, batch_size=32):
    """
    Extract features from frames using VGG16.
    
    Args:
        frame_dir (str): Directory containing frames
        batch_size (int): Batch size for processing
    
    Returns:
        features (np.array): Extracted features
        labels (np.array): Corresponding labels
    """
    # Load VGG16 model without top layers
    base_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
    
    # Get list of frames
    frames = []
    labels = []
    for class_name in os.listdir(frame_dir):
        class_dir = os.path.join(frame_dir, class_name)
        if not os.path.isdir(class_dir):
            continue
            
        for frame_name in os.listdir(class_dir):
            frames.append(os.path.join(class_dir, frame_name))
            labels.append(1 if class_name == "shoplifting" else 0)
    
    # Convert labels to numpy array
    labels = np.array(labels)
    
    # Process frames in batches
    features = []
    for i in tqdm(range(0, len(frames), batch_size), desc="Extracting features"):
        batch_frames = frames[i:i + batch_size]
        
        # Load and preprocess batch
        batch_data = []
        for frame_path in batch_frames:
            img = load_img(frame_path, target_size=(224, 224))
            x = img_to_array(img)
            x = preprocess_input(x)
            batch_data.append(x)
        
        batch_data = np.array(batch_data)
        
        # Extract features
        batch_features = base_model.predict(batch_data)
        batch_features = batch_features.reshape(batch_features.shape[0], -1)
        features.extend(batch_features)
    
    features = np.array(features)
    
    # Scale features
    scaler = StandardScaler()
    features = scaler.fit_transform(features)
    
    return features, labels

In [31]:
# Create DataFrame in the tutorial's format with error checking
video_paths = []
targets = []

# First, verify the base directory exists
base_dir = "extracted_folder/DCSASS"
if not os.path.exists(base_dir):
    print(f"Error: Directory '{base_dir}' not found!")
else:
    # Get all categories and sort them for consistent processing
    categories = sorted(os.listdir(base_dir))
    print(f"Found {len(categories)} categories: {categories}")
    
    # First, collect all videos and their labels
    for category in categories:
        category_path = os.path.join(base_dir, category)
        if os.path.isdir(category_path):
            print(f"\nProcessing category: {category}")
            video_count = 0
            
            for video_dir in os.listdir(category_path):
                video_dir_path = os.path.join(category_path, video_dir)
                if os.path.isdir(video_dir_path):
                    # Convert to tutorial format path
                    formatted_path = f"data/Shoplifting/{os.path.basename(video_dir)}"
                    if not formatted_path.endswith('.mp4'):
                        formatted_path += '.mp4'
                    video_paths.append(formatted_path)
                    
                    # Set target (1 for shoplifting, 0 for normal)
                    is_shoplifting = 1 if category.lower() == "shoplifting" else 0
                    targets.append(is_shoplifting)
                    video_count += 1
            
            print(f"Added {video_count} videos from {category}")

    # Create DataFrame with the exact same structure as tutorial
    if video_paths and targets:
        df = pd.DataFrame({
            'path': video_paths,
            'target': targets
        })
        
        print("\nDataFrame created successfully:")
        print("-" * 40)
        print(f"Total videos: {len(df)}")
        print(f"Target distribution:\n{df['target'].value_counts()}")
        print("\nFirst few entries:")
        print(df.head())
    else:
        print("Error: No videos found to create DataFrame!")

Found 14 categories: ['Abuse', 'Arrest', 'Arson', 'Assault', 'Burglary', 'Explosion', 'Fighting', 'Labels', 'RoadAccidents', 'Robbery', 'Shooting', 'Shoplifting', 'Stealing', 'Vandalism']

Processing category: Abuse
Added 39 videos from Abuse

Processing category: Arrest
Added 26 videos from Arrest

Processing category: Arson
Added 22 videos from Arson

Processing category: Assault
Added 23 videos from Assault

Processing category: Burglary
Added 47 videos from Burglary

Processing category: Explosion
Added 23 videos from Explosion

Processing category: Fighting
Added 8 videos from Fighting

Processing category: Labels
Added 0 videos from Labels

Processing category: RoadAccidents
Added 76 videos from RoadAccidents

Processing category: Robbery
Added 105 videos from Robbery

Processing category: Shooting
Added 30 videos from Shooting

Processing category: Shoplifting
Added 28 videos from Shoplifting

Processing category: Stealing
Added 64 videos from Stealing

Processing category: Vandalism
Added 29 videos from Vandalism

DataFrame created successfully:
----------------------------------------
Total videos: 520
Target distribution:
target
0    492
1     28
Name: count, dtype: int64

First few entries:
                                 path  target
0  data/Shoplifting/Abuse001_x264.mp4       0
1  data/Shoplifting/Abuse003_x264.mp4       0
2  data/Shoplifting/Abuse004_x264.mp4       0
3  data/Shoplifting/Abuse006_x264.mp4       0
4  data/Shoplifting/Abuse007_x264.mp4       0